---
title: "ESTATÍSTICA"
subtitle: "Período: 2 | Nota: 89"
description: "Disciplina cursada na PUC Minas como parte do currículo de Economia, sob a orientação do(a) professor(a) Denise Pimenta Nacle Silva (Mestrado)."
categories: ["PUC Minas", "Economia", "Métodos Quantitativos e Computacionais"]
carga_horaria: 80
nota: 89
periodo: 2
toc: true
---

## Ementa
Técnicas de amostragem. Síntese numérica e gráfica de dados. Noções de probabilidade. Variáveis aleatórias. Distribuições de probabilidade: Binomial e Normal. Estimação pontual e por intervalo da média e da proporção. Teste Qui-quadrado para tabelas de dupla entrada.

## Objetivos
**Objetivos Gerais:**
*   Estabelecer a base estatística do aluno, que abrange a análise descritiva e exploratória de dados, as noções básicas de probabilidade, os principais modelos de probabilidade e a inferência estatística;
*   Reconhecer a necessidade do uso de métodos estatísticos em determinadas disciplinas do curso, bem como identificar qual método usar.

**Objetivos Específicos:**
Ao final da disciplina o aluno será capaz de:
*   Descrever adequadamente um conjunto de dados;
*   Analisar situações onde a probabilidade pode ser usada para avaliar riscos e tomar as melhores decisões;
*   Identificar os modelos Binomial e Normal;
*   Estabelecer predições por intervalo de parâmetros populacionais;
*   Estabelecer relação de dependência (ou não) entre variáveis qualitativas;
*   Associar o conhecimento adquirido na disciplina à solução de problemas reais;
*   Tomar decisões na presença de incerteza.

## Métodos Didáticos
*   Apresentação do cronograma da disciplina no primeiro dia de aula;
*   Material escrito disponível ao aluno para o acompanhamento das aulas;
*   Elaboração de atividades avaliativas (ou não) para fixação do conteúdo, com esclarecimento de dúvidas;
*   Aulas expositivas dialogadas; trabalhos individuais e em grupo;
*   Uso de ferramentas tecnológicas: Excel, calculadoras.

## Unidades de Ensino
**Unidade 1 - Conceitos Básicos e Técnicas de Amostragem (06 horas/aula)**
Nessa unidade, o aluno será capaz de:
*   Diferenciar População e Amostra;
*   Classificar as variáveis em estudo;
*   Identificar as diferentes técnicas de amostragens aleatórias;
*   Usar uma Tabela de Números Aleatórios.
*   Bibliografia: Larson, capítulo 1.
*   Atividade de Fixação: Lista 1
*   Tópicos da Unidade:
    1.1. Conceitos básicos;
    1.2. Classificação de variáveis;
    1.3. Técnicas de amostragens aleatórias (simples, estratificada, sistemática e por conglomerados).

**Unidade 2 - Estatística Descritiva (18 horas/aula)**
Nessa unidade o aluno será capaz de:
*   Sintetizar e analisar um conjunto de dados usando construções gráficas e tabulares, e calculando medidas estatísticas.
*   Aplicar o conhecimento em uma Atividade Prática onde poderá gerar os resultados no Excel e/ou calculadora.
*   Bibliografia: Larson, capítulo 2.
*   Atividades de Fixação: Lista 2 (Dados Qualitativos) e Lista 3 (Dados Quantitativos); Atividade Prática I (Unidades 1 e 2).
*   Tópicos da Unidade:
    2.1. Síntese de dados qualitativos:
        2.1.1. Construção de tabelas de classificação simples;
        2.1.2. Construção e interpretação de tabelas de dupla classificação, calculando os percentuais em relação aos totais das linhas, aos totais das colunas e em relação ao total geral;
        2.1.3. Representações Gráficas: barras, colunas, setores e linha;
    2.2. Síntese de Dados Quantitativos:
        2.2.1. Diagrama de Pontos e Ramo-e-folhas;
        2.2.2. Construção de uma tabela de frequências e do histograma.
    2.3. Medidas Estatísticas
        2.3.1. Medidas de tendência central: média, mediana e moda;
        2.3.2. Separatrizes: Quartis;
        2.3.3. Medidas de variabilidade: amplitude total, amplitude interquartílica, variância, desvio padrão e coeficiente de variação.
    2.4. Construção do Diagrama em Caixa (Boxplot).

**Unidade 3 - Probabilidade (14 horas/aula)**
Nessa unidade o aluno será capaz de:
*   Distinguir a diferença entre calcular probabilidades de eventos compostos pela união, pela interseção e pela condição;
*   Resolver problemas que envolvam eventos independentes;
*   Usar a Regra de Bayes para calcular e interpretar as probabilidades condicionais;
*   Manipular probabilidades para avaliar riscos e tomar as melhores decisões.
*   Bibliografia: Larson, capítulo 3.
*   Atividades de Fixação: Listas 4A e 4B; Atividade Prática II (Unidade 3).
*   Tópicos da Unidade:
    3.1. Conceitos Importantes: experimento aleatório, espaço amostral, eventos;
    3.2. Definições de probabilidade: clássica e frequentista;
    3.3. Probabilidade da União, da Interseção e Condicionada. Eventos independentes;
    3.4. Regra da Multiplicação;
    3.5. Regra da Probabilidade Total;
    3.6. Regra de Bayes.

**Unidade 4 - Variáveis Aleatórias Discretas (10 horas/aula)**
Nessa unidade o aluno será capaz de:
*   Determinar a Distribuição de Probabilidades, a Função de Distribuição Acumulada, a Média, a Variância e o Desvio-padrão de uma Variável Aleatória Discreta;
*   Usar as propriedades da Esperança Matemática e da Variância;
*   Reconhecer a necessidade de usar o Modelo Binomial na solução de problemas.
*   Bibliografia: Larson, capítulo 4.
*   Atividades de Fixação: Listas 5 e 6A.
*   Tópicos da Unidade:
    4.1. Distribuição de Probabilidades e Função de Distribuição Acumulada;
    4.2. A Esperança Matemática, a Variância e o Desvio-padrão;
    4.3. Propriedades da Esperança Matemática e da Variância;
    4.4. Distribuição Binomial.

**Unidade 5 - Variáveis Aleatórias Contínuas (06 horas/aula)**
Nessa unidade o aluno será capaz de:
*   Identificar a necessidade de usar a Distribuição Normal na solução de problemas;
*   Reconhecer situações de Aproximações Normais para Distribuições Binomiais.
*   Bibliografia: Larson, capítulo 5.
*   Atividades de Fixação: Lista 6B. Atividade Prática III (Unidades 4 e 5).
*   Tópicos da Unidade:
    5.1. Função densidade de probabilidade;
    5.3. Distribuição Normal;
    5.4. Aproximações Normais para Distribuições Binomiais.

**Unidade 6 - Estimação (10 horas/aula)**
Nessa unidade o aluno será capaz de:
*   Identificar e analisar situações que necessitam do uso da Inferência Estatística;
*   Gerar e interpretar intervalos de confiança em situações onde a inferência é baseada na média;
*   Gerar e interpretar intervalos de confiança em situações onde a inferência é baseada na proporção;
*   Calcular o Tamanho da Amostra quando deseja-se estimar uma média ou uma proporção.
*   Bibliografia: Larson, capítulo 5 (item 5,4) e capítulo 6.
*   Atividades de Fixação: Listas 7 e 8.
*   Tópicos da Unidade:
    6.1. Conceitos básicos: amostra aleatória, estatística, estimador e estimativa;
    6.2. Estimação pontual da média e da proporção;
    6.3. Distribuição amostral da média: teorema central do limite;
    6.4. Intervalo de confiança para a média populacional - desvio padrão populacional conhecido. Cálculo do tamanho da amostra;
    6.5. Intervalo de confiança para a média populacional - desvio padrão populacional desconhecido;
    6.6. Intervalo de confiança para a proporção populacional. Cálculo do tamanho da amostra.

**Unidade 7 - Testes Qui-quadrado (06 horas/aula)**
Nessa unidade o aluno será capaz de:
*   Formular as hipóteses de um Teste Qui-quadrado de Homogeneidade, calcular a estatística de teste e concluir de acordo com o contexto do problema;
*   Formular as hipóteses de um Teste Qui-quadrado de Independência, calcular a estatística de teste e concluir de acordo com o contexto do problema.
*   Bibliografia: Larson, capítulo 10.
*   Atividades de Fixação: Lista 9. Atividade Prática IV (Unidades 6 e 7).
*   Tópicos da Unidade:
    7.1. Teste Qui-quadrado de homogeneidade;
    7.2. Teste Qui-quadrado de independência.

**Avaliações (10 horas/aula)**

## Processo de Avaliação
*   1ª prova parcial: 25 pontos
*   2ª prova parcial: 25 pontos
*   Trabalhos Práticos: 20 pontos (5 pontos cada um). Será planejada uma atividade caso haja necessidade de complementação de carga horária.
*   Prova Final: 30 pontos
*   Prova Substitutiva: 25 pontos
*   Prova de Reavaliação: 30 pontos

**Observações:**
1. A Prova Substitutiva tem como objetivo atender aos casos de não comparecimento em uma das duas provas parciais, bem como melhorar uma das notas obtidas em uma das avaliações parciais. Essa avaliação engloba o conteúdo referente às duas provas parciais.
2. Os alunos que não obtiverem 60 pontos, terão direito a uma Prova de Reavaliação, valendo 30 pontos, em substituição à Prova Final. A prova de Reavaliação engloba todo o conteúdo do semestre.

## Observações
**Complementação de Carga Horária:**
Caso o período letivo não seja suficiente para integralizar a carga-horária da disciplina, os alunos participarão de atividades visando a complementação da respectiva carga-horária.

## Descrição da Bibliografia Básica
*   LARSON, Ron; FARBER, Elizabeth. Estatística aplicada. 6. ed. São Paulo: Pearson Education do Brasil, c2016. *E-book*. ISBN 9788543004778.
*   LEVINE, David M.; STEPHAN, David; SZABAT, Kathryn A. Estatística: teoria e aplicações usando Microsoft Excel em português. 7. ed. Rio de Janeiro, RJ: LTC - Livros Técnicos e Científicos, c2016. *E-book*. ISBN 9788521631972.
*   MATEMÁTICA E ESTATÍSTICA EM FOCO. Uberlândia: Universidade Federal de Uberlândia, 2013-. Semestral. ISSN 2318-0552. Disponível em: http://www.seer.ufu.br/index.php/matematicaeestatisticaemfoco. Acesso em: 10 set. 2018.
*   TRIOLA, Mario F.. Introdução à estatística. 12. ed. Rio de Janeiro: LTC - Livros Técnicos e Científicos, c2017. *E-book*. ISBN 9788521634256.

## Descrição da Bibliografia Complementar
*   ANDERSON, David Ray *et al.* Estatística aplicada a administração e economia. 5. ed. São Paulo: Cengage Learning, c2021. *E-book*. ISBN 9786555583991.
*   CADERNOS DO IME: série estatística. Rio de Janeiro, RJ: Universidade do Estado do Rio de Janeiro, Semestral. ISSN 1413-9022. Disponível em: https://www.e-publicacoes.uerj.br/index.php/cadest/index. Acesso em: 30 abr. 2019.
*   DOANE, David P.; SEWARD, Lori Welte. Estatística aplicada à administração e economia. 4. ed. Porto Alegre, RS: AMGH, 2014. *E-book*. ISBN 9788580553949.
*   FREUND, John E.. Estatística aplicada: economia, administração e contabilidade. 11. ed. Porto Alegre: Bookman, 2007. *E-book*. ISBN 9788577800636.
*   MOORE, David S.; NOTZ, William; FLIGNER, Michael A.. A estatística básica e sua prática. 7. ed. Rio de Janeiro: LTC, c2017. *E-book*. ISBN 9788521634294.
*   MORETTIN, Pedro Alberto; BUSSAB, Wilton de Oliveira. Estatística básica. 9. ed. São Paulo: Saraiva, c2017. *E-book*. ISBN 9788547220228.
