---
title: "SOCIOLOGIA DAS ORGANIZAÇÕES"
subtitle: "Nota: 87 | Período: 2"
description: "Disciplina cursada na PUC Minas como parte do currículo de Economia, sob a orientação do(a) professor(a) Rogério Pádua Cavalcanti (Mestrado)."
categories: ["PUC Minas", "Sociologia", "Economia"]
carga_horaria: 40
nota: 87
periodo: 2
toc: true
---

## Ementa
As organizações como fenômeno da sociedade moderna. As Relações de Trabalho. Relação do indivíduo com a Organização. Aspectos culturais, políticos e socioambientais envolvendo as Organizações.

## Objetivos
Apresentar os conceitos básicos da sociologia clássica e da sociologia das organizações.

## Métodos Didáticos
Aulas expositivas e participativas utilizando recursos da NET.

## Unidades de Ensino
I - Conceitos básicos da Sociologia Clássica
II - O Conceito de Cultura e Cultura Organizacional
III - Aplicando os Conceitos sócio-antropológicos na análise de organizações

## Processo de Avaliação
*   3 provas de 20 pontos relativas aos clássicos da Sociologia totalizando 60 pontos;
*   1 Prova Global de 30 pontos relativa à ultima unidade
*   1 Trabalho sobre temas da unidade 3. Pod Cast 10
*   1 Prova de Reavaliação de 30 pontos relativa ao conteúdo de todo o semestre.

## Descrição da Bibliografia Básica
*   ANTUNES, Ricardo L. C.. Adeus ao trabalho?: ensaio sobre as metamorfoses e a centralidade do mundo do trabalho. São Paulo: Cortez, 2016. *E-book*. ISBN 9788524924439.
*   COELHO, Edmundo Campos et al. Sociologia da burocracia. 4. ed. Rio de Janeiro: Zahar, 1978. 153p., Nº de Exemplares: 1.
*   QUINTANEIRO, Tania; BARBOSA, Maria Ligia de Oliveira; OLIVEIRA, Márcia Gardênia Monteiro de. Um toque de clássicos: Durkheim, Marx e Weber. 2. ed. rev. e atual. Belo Horizonte: Ed. UFMG, 2009. 157 p. ISBN 9788570413178., Nº de Exemplares: 14.
*   REVISTA BRASILEIRA DE CIÊNCIAS SOCIAIS. São Paulo: Associação Nacional de Pós-Graduação e Pesquisa em Ciências Sociais,1986-. Quadrimestral. ISSN 0102-6909. Disponível em: http://www.scielo.br/scielo.php/script_sci_serial/lng_pt/pid_0102-6909/nrm_iso. Acesso em: 27 set. 2019.

## Descrição da Bibliografia Complementar
*   DADOS : revista de ciências sociais. Rio de Janeiro: IUPERJ-Instituto Universitário de Pesquisas do Rio de Janeiro,1966-. Trimestral. ISSN 0011-5258. Disponível em: http://www.scielo.br/scielo.php?script=sci_serial&pid=0011-5258&lng=en&nrm=iso. Acesso em: 9 jul. 2018.
*   DURKHEIM, Émile. Educação e sociologia. 2. São Paulo Grupo Almedina 2018 1 recurso online ISBN 9789724422107.
*   FLEURY, Maria Tereza Leme; FISCHER, Rosa Maria. Cultura e poder nas organizações. São Paulo: Atlas, 1989. 170p. ISBN 8522405077., Nº de Exemplares: 2.
*   NIZET, Jean. Sociologia de Erving Goffman. Editora Vozes 170 ISBN 9788532653062.
*   WEBER, Max. Conceitos sociológicos fundamentais. 2. São Paulo Grupo Almedina 2018 1 recurso online ISBN 9789724422534.
