---
title: "GESTÃO PÚBLICA A"
subtitle: "Período: 1 | Nota: 93"
description: "Disciplina cursada na UFMG como parte do currículo de Gestao Publica, sob a orientação do(a) professor(a) Geralda Luiza de Miranda (Doutorado)."
categories: ["UFMG", "Gestao Publica", "Gestão e Políticas Públicas"]
carga_horaria: 60
nota: 93
periodo: 1
toc: true
---

## Ementa
Gestão Pública: origens, evolução, formatos organizacionais – patrimonialismo, administração burocrática, Nova Gestão Pública, governança participativa. Gestão privada e gestão pública: distinção. Relação entre gestão pública e política. Noções de controle público e accountability. Histórico da gestão pública no Brasil.

## Descrição da Bibliografia Básica
*   BEHN, Robert. O novo paradigma da gestão pública e a busca da accountability democrática. Revista de Serviço Público. Brasília, ano 49, n. 4, 1998. Disponível em: https://search.proquest.com/openview/bab539905d3e32d7605713943a788ab6/1?pqorigsite=gscholar&cbl=2045880
*   BRASIL, IPEA. Estado, Instituições e Democracia: república. Brasília: IPEA, 2010, (Série Eixos Estratégicos do Desenvolvimento Brasileiro: Fortalecimento do Estado, das Instituições e da Democracia). Disponível em: http://www.ipea.gov.br/portal/index.php?option=com_content&view=article&id=6533
*   BRESSER-PEREIRA, Luiz Carlos. “Da administração pública burocrática à gerencial”. In: Luiz Carlos Bresser-Pereira; Peter Spink (orgs.). Reforma do Estado e administração pública gerencial. Rio de Janeiro: FGV, 2001.
*   CAMPELO, Graham Stephan. Administração pública no Brasil: ciclos entre patrimonialismo, burocracia e gerencialismo, uma simbiose de modelos. Revista Ciência & Trópico. Receife, v. 34, n. 2, 2010. Disponível em: https://periodicos.fundaj.gov.br/CIC/article/viewFile/871/592.
*   DINIZ, Eli. “Globalização, reforma do Estado e teoria democrática contemporânea”. São Paulo em Perspectiva, vol. 15, nº 4, 2001.
*   FERES JR., João. “Interesse público”. In: Leonardo Avritzer, et alli. (org.). Corrupção: ensaios e crítica. Belo Horizonte: Editora UFMG, 2008.
*   GIOVANNI, Geraldo Di; NOGUEIRA, Marcos Aurélio (orgs.). Dicionário de Políticas Públicas. São Paulo: editora UNESP/ Fundap, 2ª ed. 2015.
*   LASSWELL, Harold. “O Interesse público: sugestões de princípios e de método”. In: Carl J. Friedrich (org.). O interesse público. São Paulo: O Cruzeiro, 1962.
*   LOUREIRO, Maria Rita; TEIXEIRA, Marco Antônio Carvalho; MORAES, Tiago Cacique. “Democracia e reforma do Estado: o desenvolvimento institucional dos tribunais de contas no Brasil Recente”. Revista de Administração Pública, ago. 2009, vol. 43, nº 4, p. 739-772.
*   LOPEZ, Félix Garcia. “Accountability e controle Social na administração pública federal”. In: Fábio de Sá Silva, et. all (orgs.). Estado, instituições e democracia: democracia. Brasília: IPEA, 2010.
*   LOPEZ, Félix Garcia. “Práticas corruptas, estratégias de combate e normas sociais”. Cadernos Adenauer, nº 3, 2011.
*   MOTTA, Paulo Roberto. O estado da arte da gestão pública. Revista de Administração de Empresas – RAE, São Paulo, v. 53, n. 1, 2013. Disponível em: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0034-75902013000100008.
*   O’DONNELL, Guillermo. “Accountability horizontal e novas Poliarquias”. Lua Nova, nº 44, 1998.
*   OLIVIERI, Cecília. A lógica política do controle interno. São Paulo: Annablume. Fapesp, 2010, caps. 1 e 3.
*   PACHECO, Regina Silvia. “A agenda da nova gestão pública”. In: Maria Rita Loureiro, et. all (orgs.). Burocracia e política no Brasil. Rio de Janeiro: FGV, 2010.
*   PEREIRA, Luiz Carlos Bresser. As duas fases da história e as fases do capitalismo. Escola de Economia de São Paulo da Fundação Getúlio Vargas FGV-EESP. Texto para discussão n. 278, Maio de 2011.
*   PRZEWORSKI, Adam. “Sobre o desenho do Estado: uma perspectiva principal x agent”. In: Luiz Carlos Bresser-Pereira; Peter Spink (orgs.). Reforma do Estado e administração pública gerencial. Rio de Janeiro: FGV, 2001.
*   SANTOS, Clezio Saldanha dos. Introdução à gestão pública. São Paulo: Saraiva, 2006. Cap. 1.
*   TEIXEIRA, Marco Antonio Carvalho. Estado, poderes do estado e relações entre o estado e a sociedade. In: _____. Estado, governo e administração pública. Rio de Janeiro: FGV, 2012. p. 9-19.

## Descrição da Bibliografia Complementar
*   COELHO, Fernando; OLENSCKI, Antonio; CELSO, Rafael. Da letargia ao realento: notas sobre o ensino de graduação em administração pública no Brasil no entremeio da crise do estado e da redemocratização no país (1983-94). Revista de Administração Pública. Rio de Janeiro, v. 45, n. 6, 2011. Disponível em: http://www.scielo.br/scielo.php?pid=S0034-76122011000600005&script=sci_abstract&tlng=pt
*   COSTA, Frederico. Brasil: 200 anos de estado; 200 anos de administração pública; 200 anos de reformas. Revista de Administração Pública. Rio de Janeiro, v. 42, n. 5, 2008. Disponível em: http://www.scielo.br/pdf/rap/v42n5/a03v42n5.pdf
*   CUNHA, Eleonora. Democracia e controle público. In: ALMEIDA, Debora. Participação e controle social na saúde. Belo Horizonte: UFMG, 2011.
*   DE LEON, Linda. Sobre agir de forma responsável em um mundo desordenado: ética individual e responsabilidade administrativa. In: PETERS, Guy e PIERRE, Jon. Administração Pública: Coletânea. Brasília: ENAP, 2010. Disponível em: https://gbapufabc2014.files.wordpress.com/2014/07/deleon_2010_sobreagirdeformaresponsc3a1vel emummundodesordenado.pdf
*   DRUMOND, Alexandre Matos; SILVEIRA, Suely de Fátima. Predominância ou coexistência? Modelos de administração brasileira na política nacional de habitação. Encontro de Administração Pública e Governo. Salvador, 2012. p. 3-7. Disponível em: http://bibliotecadigital.fgv.br/ojs/index.php/rap/article/view/16042.
*   ROCHA, Arlindo Carvalho. Accountability na administração pública: modelos teóricos e abordagens. Contabilidade, gestão e governança. Brasília, v. 14, n. 2, 2011. Disponível em: https://cggamg.unb.br/index.php/contabil/article/viewFile/314/pdf_162
