---
title: "FUNDAMENTOS DA ANALISE POLITICA"
subtitle: "Nota: 93 | Período: 1"
description: "Disciplina cursada na UFMG como parte do currículo de Gestao Publica, sob a orientação do(a) professor(a) Cristiano Rodrigues (Doutorado)."
categories: ["UFMG", "Ciencia Politica", "Gestao Publica"]
carga_horaria: 60
nota: 93
periodo: 1
toc: true
---

## Ementa
Política, estado, democracia, autoridade, legitimidade, público / privado, sociedade civil, justiça, participação, representação. Estado e mercado como diferentes mecanismos de alocação de recursos. Definições de democracia. Divisão dos poderes, “accountability” e responsividade. Estado, racionalidade e burocracia. As transformações do papel do Estado. Inovações institucionais da democracia.

## Descrição da Bibliografia Básica
*   ANDERSON, Perry. “Balanço do Neoliberalismo”. Em Emir Sader (org.). Pós-neoliberalismo: as políticas sociais e o Estado Democrático. São Paulo: Editora Paz e Terra, 1996. Disponível em: www.unirio.br/unirio/cchs/.../politica...1-balanco-do-neoliberalismo-anderson/.../file
*   ARENDT, Hannah. “O que é Política?” In: O que é política? 3ª Edição. São Paulo: Editora Bertrand Brasil, 1998 (p. 21 a 85). Disponível em: http://cmapspublic.ihmc.us/rid=1PYFMTQP9-22F8RWK-2JWC/ARENDT,%20Hannah.%20O%20que%20%C3%A9%20pol%C3%ADtica.pdf
*   BONAVIDES, Paulo. Ciência Política. São Paulo, Malheiros Editores, 1993. Disponível em: http://www.ebah.com.br/content/ABAAAfDA0AK/paulo-bonavides-ciencia-politica?part=11
*   BOBBIO, N. Estado, Governo, Sociedade - Para uma teoria geral da política. RJ: Paz e Terra, 1987. Cap. III - itens: 2, 3, 4, 5, 6 e 7. Disponível em: http://www.ufjf.br/virgilio_oliveira/files/2014/10/Texto-21-Bobbio-2007.pdf
*   CARDOSO SILVA, Vera Alice. “A natureza e as formas de manifestação do poder político: debates teóricos”, In: O Poder em Perspectiva, Renarde Freire Nobre et al., PET Ciências Sociais (Org.), Sografe Editora, 2012, p. 89 a 109.
*   CARDOSO Jr., José Celso (Coord. Geral). Projeto Perspectivas do Desenvolvimento Brasileiro, Brasília: IPEA, 2010. Disponível em: https://repositorio.ipea.gov.br/handle/11058/3189?mode=full
*   CODATO, Adriano e PERISSINOTTO, Renato M. "Marxismo e Elitismo: Dois modelos antagônicos de análise social?". In: Revista Brasileira de Ciências Sociais, vol. 24, nº 71, 2009.
*   DUARTE, Clenício. “A Concepção Moderna de Democracia e o Primado do Direito Administrativo”. In: Revista do Serviço Público, Brasília (60) 4: 415-418, Out.Dez. de 2009. Disponível em: https://revista.enap.gov.br/index.php/RSP/article/download/34/31
*   KOHAN, Néstor. "Gramsci e Marx: hegemonia e poder na teoria marxista. "Tempos Históricos, nº 10, p. 15-70, 2007. Disponível em: http://erevista.unioeste.br/index.php/temposhistoricos/article/view/1223
*   LOPES, Felix Garcia. “Accountability e Controle Social na administração Pública Federal”. In: Estado, Instituições e Democracia: Democracia. CARDOSO Jr., José Celso (Coord. Geral). 2010. Projeto Perspectivas do Desenvolvimento Brasileiro, Brasília: IPEA, 2010, p. 185 a 210. Cap. 5.
*   MAIA, Antônio C. “Sobre a analítica do poder de Foucault”. Rev. Tempo Social; Rev. Sociol. USP, S. Paulo, 7(1-2): 83-103, outubro de 1995. Disponível em: http://www.scielo.br/pdf/ts/v7n1-2/0103-2070-ts-07-02-0083.pdf
*   MANIN, Bernard. As Metamorfoses do Governo Representativo. Disponível em: https://edisciplinas.usp.br/pluginfile.php/4418905/mod_resource/content/1/Manin%20-%20Metamorfoses%20do%20governo%20representativo%20%28artigo%29.pdf
*   MATOS, Marlise. “Inclusão Democrática No Brasil Contemporâneo: desafios de uma agenda inconclusa”. In: Introdução à Teoria Democrática: conceitos, histórias, instituições e questões transversais. Mendonça, Ricardo Fabrino e Cunha, Eleonora S. Martins., Belo Horizonte, Editora da UFMG, 2018, p.263 a 288.
*   MIGUEL, Luis Felipe. “A democracia domesticada: bases antidemocráticas do pensamento democrático contemporâneo”. Revista Dados, Rio de janeiro, vol. 45, nº 3, p. 483-511, 2002. Disponível em: <http://www.scielo.br/pdf/dados/v45n3/a06v45n3.pdf>.
*   MOREIRA, Marcelo Sevaybricker. A democracia no pensamento político e social brasileiro do século XX: Tradições e intelectuais do país. In: Mendonça e Cunha. Introdução a Teoria Democrática: conceitos, histórias, instituições e questões transversais. Editora UFMG. Belo Horizonte, 2018.
*   PITIKIN, Hanna. O conceito de representação. IN: Cardoso, F. H. e Martins, C. E. (orgs.) Política e Sociedade. SP: Cia Editora Nacional, 1979.
*   PRZEWORSKI, Adam. “Amas a Incerteza é Serás democrático”. Novos Estudos Cebrap, n.º 9, p. 36- 46, jul. 1984. Disponível em: http://novosestudos.uol.com.br/v1/contents/view/161.
*   RENNÓ, Lucio. “Responsividade e Qualidade da Democracia: Eleitores e Representantes no Nível Federal”. In: Instituições e Democracia: Democracia e Estado. Brasília: IPEA, 2010. Cap.2.
*   RIBEIRO, Renato Janine. A democracia. Publifolha, 2001. Disponível em: https://www.academia.edu/12000175/A_Democracia_Renato_Janine_Ribeiro
*   WEBER, Max. Três Tipos Puros de Poder Legítimo. Tradução de Artur Morão. O ensaio, encontrado no espólio do autor, foi postumamente publicado por Marianne Weber nos Preußischen Jahrbücher, Vol. CLXXXVII, 1922, p. 1-12, com o subtítulo: Um estudo sociológico. Disponível em: http://www.lusosofia.net/textos/weber_3_tipos_poder_morao.pdf

## Descrição da Bibliografia Complementar
*   ALMEIDA, D. C. R. Metamorfose da representação política: lições práticas dos conselhos de saúde no Brasil. In: AVRITZER, L. (Org.). A dinâmica da participação no Brasil. São Paulo: Cortez Editora, 2010.
*   AVRITZER, L.; PEREIRA, M. L. D. Democracia, participação e instituições híbridas. Teoria & Sociedade, número especial, 2005.
*   AVRITZER, L.; SANTOS, B. Introdução: para ampliar o cânone democrático. In: SANTOS, B. (Org.). Democratizar a democracia: os caminhos da democracia participativa. Rio de Janeiro: Civilização Brasileira, 2006, p. 39-80.
*   BOBBIO, N., Matteucci, N. & Pasquino, G. Dicionário de Política. Brasília: Ed. UNB, 1991. Verbetes: Política (itens: I a V) e Poder (itens: I e VII)
*   BENEVIDES, M. V. M. A cidadania ativa: referendo, plebiscito e iniciativa popular. São Paulo: Ática, 1991.
*   DAGNINO, E. (Org.). Sociedade Civil e Espaços Públicos no Brasil. RJ: Paz e Terra, 2002.
*   DAHL, Robert. Sobre a democracia. Brasília: UNB, 2001.
*   DAHL, Robert. Poliarquia: participação e oposição. São Paulo: EDUSP, 1997. p. 25-50.
*   FINLEY, M. I. Democracia Antiga e Moderna. RJ: ED. Graal, 1988.
*   WEBER, Max. Ciência e Política Como Vocação. RJ: Ed. Guanabara, 1981.
*   MANIN, Bernard; PRZEWORSKI, Adam; STOKES, S. Eleições e Representação. Lua Nova, São Paulo, 67: 105-138, 2006.
*   O’DONNELL, G. Accountability horizontal e novas poliarquias. Lua Nova, 44, p. 27-53, 1998.
*   PATEMAN, C. Participação e teoria democrática. Rio de Janeiro: Paz e Terra, 1992.
*   SANTOS, B. S. Reinventar a democracia. Lisboa: Gradiva, 1998.
*   SARTORI, Giovanni. A teoria democrática revisitada. Vol. I. Ed. Ática, 1994. Capítulos: 6 e 8.
*   URBINATTI, N. O que torna a representação democrática? In: O Futuro da Representação.Revista Lua Nova, n. 67, 1996.
