---
title: "SOCIOLOGIA DAS ORGANIZACOES PUBLICAS"
subtitle: "Período: 2"
description: "Disciplina em andamento na UFMG como parte do currículo de Gestao Publica, sob a orientação do(a) professor(a) Ludmila Mendonca Lopes Ribeiro (Doutorado)."
categories: ["UFMG", "Sociologia", "Gestao Publica"]
carga_horaria: 60
periodo: 2
toc: true
---

## Ementa
Burocracia, administração pública. Estado, relações sociais. Institucionalismo, utilitarismo. Burocracia, poder político. Cultura organizacional. Mudança, flexibilização organizacional.

## Descrição da Bibliografia Básica
*   BOUDON, R, BOURRICAUD, F, Dicionário crítico de sociologia, Ática, SP, 2001, p.253-260
*   DIAS, R, Sociologia das organizações, Atlas, SP, 2008, 69-144
*   WEBER, M, Economia y sociedad, Fondo de cultura econômica, México, 2004, p.5-45, p.170-203, p.1047-1095
*   MERTON, R, Burocracia e personalidade, org, de Campos, E. Sociologia da Burocracia, Zahar, RJ, 1978, p.107-124
*   BEETHAM, D, A burocracia e a teoria democrática, Estampa, Lisboa, 1988, p.137-175
*   SELZNICK, P. Fundamentos da teoria das organizações, org. de ETIZIONI. A. Organizações Complexas, Atlas, SP, 1967, p.30-42
*   MARCH, J, SIMON, H, Teoria das organizações, FGV, RJ, 1972, p.192-238
*   PERROW, C. Análise organizacional, Atlas, SP. 1972, p.73-119
*   CHAMPION, D, A sociologia das organizações, Saraiva, 1979, SP, 116-132

## Descrição da Bibliografia Complementar
*   ALVES, D, O teste sociométrico, sociogramas, Globo, Porto Alegre,1972, p.14-18.
*   FOUCAULT, M, Vigiar e punir, Vozes, RJ, 1986, p.125-152.
*   MELLO E SOUSA, L, Raymundo Faoro e ‘Os donos do poder’ in Introdução ao Brasil, vol 1, org. de Mota, L, Senac, SP. 2004, p.335-356.
*   BASTOS, E.R. “Gilberto Freyre – Casa-grande & senzala” in Mota (org.), op. cit. p.215-234.
*   SALLUM JR, B. “Sérgio Buarque de Holanda - Raízes do Brasil” in Mota (org.), op. cit. p.235-256.
*   LAPA, J.R.A.: “Caio Prado Júnior – Formação do Brasil contemporâneo” in Mota (org.), op. cit. p.257-272.
*   LAMOUNIER, B: “Vítor Nunes Leal – Coronelismo, enxada e voto” in Mota (org.), op. cit. p. 273-292.
*   ALMEIDA, M.H.T. “Oliveira Viana – Instituições políticas brasileiras” in Mota (org.), op. cit. p. 293-314.
*   SORJ, B. A nova sociedade brasileira, Jorge Zahar Ed. R.J. 2000.
*   GOFFMAN, E. Manicômios, prisões e conventos, Perspectiva, SP, 2007, p.99-108, p.246-260.
*   MEYER, J, ROWAN, B, Estrutura como mito e cerimônia.
*   PFEFFER, J, Organizaciones y teoria de las organizaciones, fondo de cultura econômica, México, 1992, p.276-320.
*   FREITAS, M, E, Cultura organizacional, Makron books, SP. 1991, p.12-37.
*   MICHELS, R, A tendência burocrática dos partidos políticos in Campos, op. cit. p.101-106.
*   TRAGTEMBERG, M, Burocracia e ideologia, Ática, SP, 1977, 58-89
