---
title: "ESTATÍSTICA MULTIVARIADA"
subtitle: "Período: 5"
description: "Disciplina em andamento na PUC Minas como parte do currículo de Economia, sob a orientação do(a) professor(a) Mayra Alves Stradioto (Mestrado)."
categories: ["PUC Minas", "Quantitativo", "Economia"]
carga_horaria: 40
periodo: 5
toc: true
---

## Ementa
Regressão Multivariável. Regressão Múltipla. Regressão Logística. Análise de Componentes Principais. Decomposição em Valor Singular. Análise de Fator. Análise Discriminante. Anova e Manova.

## Objetivos
*   Dar ao estudante os fundamentos básicos da estatística Multivariada, mostrando operações nas diversas áreas do conhecimento;
*   Capacitar o aluno a raciocinar estatisticamente em duas ou mais dimensões de variáveis;
*   Incentivar a utilização da informática para soluções de problemas.

## Métodos Didáticos
*   Aulas expositivas;
*   Listas de exercícios;
*   Trabalhos práticos.

## Unidades de Ensino
| Matéria Prevista | Quantidade de Aulas |
| :--- | :--- |
| **Unidade 0 Nivelamento** | 2 |
| 0.1 Operação com vetores | |
| 0.2 Operação com Matrizes | |
| **Unidade 1 Introdução** | 2 |
| 1.1 Aplicação das Técnicas Multivariadas | |
| 1.2 Organização dos dados | |
| **Unidade 2 Componentes Principais** | 6 |
| 2.1 - Teorema da decomposição Espectral | |
| 2.2 - Contrução das Componetes Princiapais | |
| 2.3 - Proporção Explicadas Pelas Componentes | |
| 2.4 - Aplicações | |
| **Unidade 3 Análise Fatorial** | 8 |
| 3.1 - Apresentação Teórica da Metodologia | |
| 3.2 Modelo de Fatores Ortogonais | |
| 3.3 Estimação dos Fatores | |
| 3.4 - Aplicações | |
| **Unidade 4 Regressão Linear Multivariada** | 8 |
| 4.1 Matriz de correlação | |
| 4.2 Estimação do Modelo | |
| 4.3 Qualidade de Ajuste e ANOVA | |
| 4.3 Aplicações | |
| **Unidade 5 Regressão Logística** | 8 |
| 5.1 Tabela de Contingência | |
| 5.2 Estimação do Modelo | |
| 5.3 Validação do modelo | |
| 5.4 Aplicações | |
| **Provas individuais** | 6 |

## Processo de Avaliação
*   2 provas individuais: 30 pontos cada
*   2 Trabalhos dirigidos: 20 pontos cada
*   Reavaliação 30 pontos (substitui a menor nota das duas primeiras provas individuais)

## Observações
**Bibliografia Básica**

*   HAIR, Joseph F et al. Análise multivariada de dados. 6. ed. Porto Alegre, RS: Bookman, 2009. E-book. ISBN 9788577805341.
    *Justificativa: O livro apresenta autores nacionais que oferece uma abordagem acessível. Apresenta estudos de casos sobre questões atuais e está em formato eletrônico.*

*   STOCK, James H.; WATSON, Mark W. Econometria. São Paulo, SP: Pearson, 2004. E-book. ISBN 8588639149.
    *Justificativa: O livro oferece uma abordagem acessível na área de econometria, aborda temas de regressão lineares e não lineares.*

*   MANLY, Bryan F. J.; ALBERTO, Jorge A. Navarro. Métodos estatísticos multivariados: uma introdução. 4. ed. Porto Alegre, RS: Bookman, 2019. E-book. ISBN 9788582604991.
    *Justificativa: O livro oferece uma abordagem acessível de todo o conteúdo estudado. Apresenta estudos de casos sobre questões atuais da estatística Multivariada em áreas que despertam o interesse dos. Usa o pacote estatístico Minitab e SPSS.*

*   REVISTA BRASILEIRA DE ESTATÍSTICA = BRAZILIAN JOURNAL OF PROBABILITY AND STATISTICS. Rio de Janeiro: IBGE ,1940-. Trimestral. ISSN 2675-3243 versão on-line. Disponível em: https://rbes.ibge.gov.br/index.php/volumes-recentes.
    *Justificativa: A revista aborda temas atuais na área de econometria e estudos sobre questões atuais da estatística.*

**Bibliografias Cadastradas (COMPLEMENTAR)**

*   SCHMULLER, Joseph. Análise estatística com R para leigos. Rio de Janeiro: Alta Books, 2019. E-book. ISBN 9788550807850.
    *Justificativa: É um livro que aborda aplicações simples de estatística com a utilização do pacote R.*

*   FÁVERO, Luiz Paulo; BELFIORE, Patrícia. Análise de dados: técnicas multivariadas exploratórias com SPSS e STATA. Rio de Janeiro, RJ: Elsevier, 2015. E-book. ISBN 9788595155589.
    *Justificativa: O livro oferece uma abordagem acessível de todo o conteúdo estudado. Apresenta estudos de casos sobre questões atuais da estatística Multivariada em áreas que despertam o interesse dos. Usa o pacote estatístico SPSS e STATA*

*   MORETTIN, Pedro Alberto. Econometria financeira: um curso em séries temporais financeiras. 2. ed. rev. e ampl. São Paulo: Blucher, 2011. E-book. ISBN 9788521211310.
    *Justificativa: É um livro que visa formar a base necessária para a aprendizagem de métodos estatísticos mais avançados e, por isso requer um conhecimento matemático prévio. Recomenda o uso de pacotes estatísticos como o R e o Minitab na prática dos conceitos desenvolvidos.*

*   ECONOMETRICA. Evanston: Econometric Society, Departament of Economics ,1933-. Bimestral. ISSN 1468-0262 .versão on-line. Disponível : https://onlinelibrary-wiley.ez93.periodicos.capes.gov.br/journal/14680262.
    *Justificativa: A revista aborda temas atuais na área de econometria e estudos sobre questões atuais da estatística.*

*   LOESCH, Claudio; HOELTGEBAUM, Marianne. Métodos estatísticos multivariados. São Paulo, SP: Saraiva, 2012. E-book. ISBN 9788502146105.
    *Justificativa: Livro com explicações simples e cuidadosas, possui, em vários capítulos, exercícios propostos que apresentam, resolvem exemplos e ainda fazem perguntas sobre aspectos teóricos que ultrapassam o seu escopo.*

*   ARTES, Rinaldo; BARROSO, Lúcia Pereira. Métodos multivariados de análise estatística. São Paulo, SP: Blucher, 2023. E-book. ISBN 9786555066999.
    *Justificativa: O livro oferece uma abordagem acessível de todo o conteúdo estudado. Apresenta estudos de casos sobre questões atuais da estatística Multivariada em áreas que despertam o interesse dos alunos.*

**Outras indicações:**
*   MILONE, Giuseppe. Estatística geral e aplicada. São Paulo: Pioneira Thomson Learning, 2004. 483 p. ISBN 8522103399.

## Descrição da Bibliografia Básica
*   HAIR, Joseph F. *et al.* Análise multivariada de dados. 6. ed. Porto Alegre, RS: Bookman, 2009. *E-book*. ISBN 9788577805341.
*   MANLY, Bryan F. J.; ALBERTO, Jorge A. Navarro. Métodos estatísticos multivariados: uma introdução. 4. ed. Porto Alegre, RS: Bookman, 2019. *E-book*. ISBN 9788582604991.
*   REVISTA BRASILEIRA DE ESTATÍSTICA = BRAZILIAN JOURNAL OF PROBABILITY AND STATISTICS. Rio de Janeiro: IBGE ,1940-. Trimestral. ISSN 2675-3243 versão on-line. Disponível em: https://rbes.ibge.gov.br/index.php/volumes-recentes. Acesso em: 10 set. 2018.
*   STOCK, James H.; WATSON, Mark W.. Econometria. São Paulo, SP: Pearson, 2004. *E-book*. ISBN 8588639149.

## Descrição da Bibliografia Complementar
*   ARTES, Rinaldo; BARROSO, Lúcia Pereira. Métodos multivariados de análise estatística. São Paulo, SP: Blucher, 2023. *E-book*. ISBN 9786555066999.
*   ECONOMETRICA. Evanston: Econometric Society, Departament of Economics ,1933-. Bimestral. ISSN 1468-0262 versão on-line. Disponível em: https://onlinelibrary-wiley.ez93.periodicos.capes.gov.br/journal/14680262. Acesso em: 16 out. 2020.
*   FÁVERO, Luiz Paulo; BELFIORE, Patrícia. Análise de dados: técnicas multivariadas exploratórias com SPSS e STATA. Rio de Janeiro, RJ: Elsevier, 2015. *E-book*. ISBN 9788595155589.
*   LOESCH, Claudio; HOELTGEBAUM, Marianne. Métodos estatísticos multivariados. São Paulo, SP: Saraiva, 2012. *E-book*. ISBN 9788502146105.
*   MORETTIN, Pedro Alberto. Econometria financeira: um curso em séries temporais financeiras. 2. ed. rev. e ampl. São Paulo: Blucher, 2011. *E-book*. ISBN 9788521211310.
*   SCHMULLER, Joseph. Análise estatística com R para leigos. Rio de Janeiro: Alta Books, 2019. *E-book*. ISBN 9788550807850.
