---
title: "FILOSOFIA: RAZÃO E MODERNIDADE"
subtitle: "Nota: 90 | Período: 2"
description: "Disciplina cursada na PUC Minas como parte do currículo de Economia, sob a orientação do professor(a) Angelo José Salvador (Mestrado)."
categories: ["PUC Minas", "Sociologia", "Economia"]
carga_horaria: 40
nota: 90
periodo: 2
toc: true
---

## Ementa
As origens da Filosofia. A Filosofia como busca do conhecimento. Ciência e Filosofia: o surgimento da modernidade, a racionalidade instrumental e o impacto das novas tecnologias. A questão do saber e da linguagem nas sociedades contemporâneas.

## Objetivos
*   Refletir sobre a condição moderna de existência e identificar os seus contrastes com o mundo antigo e medieval.
*   Compreender a problematização moderna acerca do conhecimento.
*   Analisar os aspectos essenciais da cientificidade moderna.
*   Exercitar a crítica filosófica em relação ao existente.

## Métodos Didáticos
1. Exposição dos conteúdos programáticos e debate sobre os temas e objetos apresentados.
2. Filmes (ficção e documentários).
3. Exercícios de reflexão.
4. Seminários.

## Unidades de Ensino
**I. Origem e desenvolvimento da filosofia**
1.1. Filosofia: origem e especificidade em relação a outras formas de conhecimento
1.2. Questões filosóficas fundamentais
    1.2.1. A filosofia pré-socrática e a busca de um princípio explicativo do mundo
    1.2.2. Platão e Aristóteles: a questão do conhecimento
    1.2.3. Período medieval e a relação entre fé e razão

**II. Filosofia e modernidade**
2.1. O que significa ser moderno? A existência moderna e seus contrastes com o mundo antigo e medieval.
2.2. Modernidade e o otimismo da razão iluminista
2.3. Pretensão de hegemonia da racionalidade instrumental

**III. A tarefa crítica da filosofia na contemporaneidade**
3.1. Conhecimento e o problema da linguagem
3.2. Saber e poder

## Processo de Avaliação
Três provas de 20, 20 e 30 pontos. 20 pontos de exercícios cumulativos e 10 pontos da prova multidisciplinar.

## Descrição da Bibliografia Básica
*   CHAUÍ, Marilena de Souza. Convite à filosofia. 14. ed. São Paulo: Ática, 2010. 520 p. ISBN 9788508134694., Nº de Exemplares: 52., Nº de Exemplares: 52., Nº de Exemplares: 51.
*   BONJOUR, Laurence; BAKER, Ann. Filosofia: textos fundamentais comentados. 2. ed. Porto Alegre: Artmed, 2010. E-book. ISBN 9788536323633.
*   MARX, Karl; ENGELS, Friedrich. Manifesto do partido comunista. 2. ed. Petrópolis, RJ: Vozes, 2014. E-book. ISBN 9788532641892.
*   SAPERE AUDE: revista do Departamento de Filosofia da Pontifícia Universidade Católica de Minas Gerais. Belo Horizonte: Ed. PUC Minas,2009-. Semestral. ISSN 2177-6342. Disponível em: http://periodicos.pucminas.br/index.php/SapereAude. Acesso em: 31 ago. 2018.

## Descrição da Bibliografia Complementar
*   HABERMAS, Jürgen. Técnica e ciência como "ideologia". Lisboa: Ed. 70, c1968. 149 p. ISBN 9789724413358., Nº de Exemplares: 2.
*   KANT, Immanuel et al. O que é esclarecimento?. Rio de Janeiro: Via Verita, 2011. 99 p. ISBN 9788564565029., Nº de Exemplares: 7.
*   KRITERION: revista de filosofia. Belo Horizonte: UFMG, Faculdade de Filosofia e Ciências Humanas,1947-. Semestral. ISSN 0100-512X. Disponível em: http://www.scielo.br/scielo.php?script=sci_serial&pid=0100-512X&lng=en&nrm=iso. Acesso em: 9 jul. 2018.
*   SOUZA FILHO, Danilo Marcondes de. Textos básicos de filosofia: dos pré-socráticos a Wittgenstein. 4. ed. Rio de Janeiro: J. Zahar, 2005. 184 p. ISBN 8571105200, Nº de Exemplares: 6.
*   SOUZA, José Carlos Aguiar de. O projeto da modernidade: autonomia, secularização e novas perspectivas. Brasília: Liber Livro, Juiz de Fora: CES/JF, 2005. 141 p. ISBN 8598843121., Nº de Exemplares: 11.
