---
title: "PROJETO: DESIGN DE NEGÓCIOS"
subtitle: "Extracurricular | Nota: 70"
description: "Disciplina cursada na PUC Minas como parte do currículo de Administracao, sob a orientação do(a) professor(a) Soraya Cardoso Pongelupe Lopes (Mestrado)."
categories: ["PUC Minas", "Administracao", "Empreendedorismo e Inovação"]
carga_horaria: 60
nota: 70
periodo: 100
toc: true
---

## Ementa
PROJETO: DESIGN DE NEGÓCIOS

## Carga Externa
A carga horária externa registrada na disciplina compreende o trabalho acadêmico efetivo realizado pelo discente, sob a supervisão do professor, realizado no próprio âmbito da disciplina, na forma de: atividades em biblioteca, iniciação científica, trabalhos individuais e em grupo, práticas de ensino, práticas de extensão, laboratórios, entre outras. Nessa perspectiva, ao professor caberá estabelecer os termos da operacionalização dessas atividades, assim como as necessárias formas de avaliação, no âmbito de suas atividades normais e rotineiras em sala de aula.
(Resolução CNE/CES Nº 3, de 02 de Julho de 2007, art. 2º, item II)

## Objetivos
**Objetivo geral:**
Os discentes devem ser capazes de desenvolver um Modelo de Negócios inovador para o mercado, usando ferramentas de design e inovação. Além de apresentar habilidades e competências, técnicas e comportamentais, para criação de negócios inovadores.

**Objetivos específicos:**
*   Desenvolver e praticar criatividade e inovação.
*   Aplicar ferramentas de design para a criação de novos negócios.
*   Identificar as dores e necessidades existentes a partir de informações do mercado.
*   Desenhar a proposição de valor para o mercado.
*   Conceber o modelo do negócio a partir da proposta de valor.
*   Desenvolver o MVP.
*   Realizar o teste e validar o MVP.
*   Avaliar o potencial de mercado do negócio. (Tamanho do mercado; potencial de vendas).
*   Realizar prática extensionista, contribuindo para o desenvolvimento econômico e social do ecossistema empreendedor local auxiliando no processo de ideação, criação de times multidisciplinares, validação da ideia e desenvolvimento do MVP.
*   Praticar a produção e disseminação das ciências, das artes e da cultura, a interdisciplinaridade e a integração entre a Universidade e a sociedade.

## Métodos Didáticos
A metodologia da disciplina de Práticas de Design de Negócios tem como aplicar os conceitos vistos na disciplina de Modelagem de Negócio em uma empresa real ou a ser implantada. A atividade de modelagem de negócio abrangerá análise de ambiente de negócio usando bases secundárias de mercado e uma pesquisa de campo com objetivo de identificar uma oportunidade de negócio para modelarmos uma proposta de negócio. Logo, a metodologia de ensino adotada será dinâmica, valendo-se de aulas expositivas dialogadas, orientações aos grupos e a prática extensionista que visa a criação de uma oportunidade real de geração de emprego e renda para os alunos e o desenvolvimento econômico e social sustentável da sociedade.
Além da construção dos projetos de negócios, os alunos contribuirão para o assessoramento à empreendimentos solidários do Projeto de Extensão Ecosol.

## Unidades de Ensino
**Unidade 1- Modelos de Negócios Inovadores (6h)**
*   Apresentação da Disciplina e Alinhamento de Expectativas
*   O processo de ideação de negócios
*   Apresentação do Projeto de Design (PNBOX - Canvas - MVP - PITCH) - Formação de Grupos e Definições dos Negócios

**Unidade 2- Aplicação de ferramentas do Design para Negócios (6h)**
*   PNBOX - Segmentação de Mercado
*   PNBOX - Gerador de Personas

**Unidade 3- Construção do Modelo de Negócio (6h)**
*   PNBOX - Proposta de Valor
*   PNBOX - Análise da Concorrência
*   Construção do Canvas Modelo de Negócio

**Unidade 4 e 5- Validação da ideia e desenho do MVP e testagem do MVP (12h)**
*   Planejamento do MVP
*   Desenvolvimento e Testes do MVP

**Unidade 6. Mecanismos de investimentos e Captação de recursos. (8h)**
*   Fontes de receitas x custos. Definição e apresentação de fontes de recursos.
*   Elaboração e apresentação do Pitchs
*   Avaliação Global
*   Reavaliação

## Processo de Avaliação
A avaliação será processual, de forma que a cada etapa da construção do projeto de design de negócio o alunos receberá o feedback. Além disso, ao final da disciplina o aluno fará uma avaliação formal. As etapas de avaliação serão:
*   Etapa 1 Modelos de Negócios Inovadores - Identificação e estudo de modelos de inovadores analisar o ambiente de negócio: 5 pts
*   Etapa 2- Aplicação de ferramentas do Design para Negócios - aplicação de ferramentas de identificação de dores e necessidades de potenciais clientes e identificação de oportunidades de negócio: 10 pts
*   Etapa 3- Construção do Modelo de Negócio - construção de proposta de valor e modelo de negócio: 10 pts
*   Etapa 4- Validação da ideia, desenho do MVP - Validação da ideia com a concorrência e planejamento de MVP: 15 pts
*   Etapa 5- Desenvolvimento e testagem do MVP: 10 pts
*   Etapa 6- Apresentação e Relatório Consolidado Vídeo do Pitch, consolidação do relatório e assessoramento aos empreendimentos solidários: 20 pts
*   Avaliação Global: 30 pts
*   Reavaliação: 30 pts

## Descrição da Bibliografia Básica
*   BESSANT, J. R.; TIDD, Joseph. Inovação e empreendedorismo. 3. ed. Porto Alegre: Bookman, 2019. *E-book*. ISBN 9788582605189.
*   DORNELAS, José Carlos Assis. Dicas essenciais de empreendedorismo: sugestões práticas para quem quer empreender. 2. ed. Barueri, SP: Atlas, 2023. *E-book*. ISBN 9786559773688.
*   DORNELAS, José Carlos Assis. Dicas essenciais de empreendedorismo: sugestões práticas para quem quer empreender. 2. ed. Barueri, SP: Atlas, 2023. *E-book*. ISBN 9786559773688.
*   REVISTA DE EMPREENDEDORISMO E GESTÃO DE PEQUENAS EMPRESAS . São Paulo, SP: ANEGEPE , Quadrimestral (4 em 4 meses). ISSN 2316-2058 versão on-line. Disponível em: http://www.regepe.org.br/regepe/index. Acesso em: 10 set. 2018.
*   TAJRA, Sanmya Feitosa. Empreendedorismo: conceitos e práticas inovadoras. 2. ed. São Paulo: Érica, 2019. *E-book*. ISBN 9788536531625.

## Descrição da Bibliografia Complementar
*   AMATO NETO, João *et al.* ESG investing:. um novo paradigma de investimentos? São Paulo: Blucher, 2022. 1 recurso online. ISBN 9786555065619.
*   CADERNOS DE GESTÃO E EMPREENDEDORISMO. Rio de Janeiro, RJ: Universidade Federal Fluminense ,2013-. Quadrimestral (4 em 4 meses). ISSN 2318-9231 versão on-line. Disponível em: https://periodicos.uff.br/cge. Acesso em: 10 set. 2018.
*   DORNELAS, José Carlos Assis. Empreendedorismo: transformando ideias em negócios. 9. ed. Barueri, SP: Atlas, 2023. *E-book*. ISBN 9786559774531.
*   FELIPE CHIBÁS ORTIZ. Criatividade, inovação e empreendedorismo. Phorte Editora, 2021. 30 p. ISBN 9786588868096.
*   JOÃO AMATO NETO; JOÃO AMATO NETO; JOÃO AMATO NETO. ESG Investing: um novo paradigma de investimentos?. Editora Blucher, 2022. 17 p. ISBN 9786555065619.
*   MODELOS de negócios. Porto Alegre SAGAH 2020 1 recurso online ISBN 9786556900438.
*   TAJRA, Sanmya Feitosa. Empreendedorismo: da ideia à ação. São Paulo: Expressa, 2020. 1 recurso online. ISBN 9788536533834.
