---
title: "ECONOMETRIA"
subtitle: "Período: 4"
description: "Disciplina em andamento na PUC Minas como parte do currículo de Economia, sob a orientação do(a) professor(a) Luciane Reis Raposo Pereira (Doutorado)."
categories: ["PUC Minas", "Economia", "Métodos Quantitativos e Computacionais"]
carga_horaria: 80
periodo: 4
toc: true
---

## Ementa
Modelos de regressão linear simples e múltiplo: especificação, estimação, inferências e predição. Modelo geral de regressão linear: especificação, estimação, inferências e predição. Violação dos pressupostos clássicos: multicolinearidade, heterocedasticidade, autocorrelação. Regressões com variáveis independentes qualitativas (variáveis binárias ou dummies). Utilização de softwares na estimação de regressões simples e múltiplas envolvendo séries econômicas. Análise dos resultados das regressões estimadas. Testes para análise das regressões estimadas: omissão e redundância de variáveis explicativas, autocorrelação, heterocedasticidade e normalidade dos resíduos.

## Objetivos
O objetivo do curso é fornecer aos alunos instrumentais teórico e prático para a análise de modelos de regressão linear simples e múltipla envolvendo variáveis econômicas.

## Métodos Didáticos
Aulas expositivas teóricas e práticas e trabalhos individuais e em grupo.

## Unidades de Ensino
**0. Nivelamento**
Revisão de conceitos básicos de estatística e álgebra matricial.

**1. Regressão linear simples (modelo clássico)**
1.1. Construção de um Modelo Econométrico: Etapas e Procedimentos
1.2. Hipóteses Básicas do Modelo Clássico de Regressão
1.3. Estimação através do Método dos Mínimos Quadrados
1.4. Decomposição Amostral da Variável Dependente
1.5. Inferência estatística: teste de hipóteses, intervalos de confiança para os estimadores e previsão
1.6. Adequação de modelos não lineares à regressão linear

**2. Regressão linear múltipla (abordagem do modelo geral de regressão linear)**
2.1. Hipóteses Básicas
2.2. Estimação dos parâmetros através dos Mínimos Quadrados
2.3. Teste de significância global e parcial
2.4. Intervalos de confiança

**3. Variável dummy**
3.1. Regressões utilizando variável independente qualitativa: variável dummy ou binária.
3.2. Forma de inclusão das variáveis dummies no modelo.

**4. Violação dos pressupostos clássicos**
4.1. Multicolinearidade: identificação, conseqüências e possíveis soluções
4.2. Autocorrelação: natureza do problema, conseqüências, diagnóstico (teste de Durbin-Watson e LM) e correção (método de mínimos quadrados generalizados)
4.3. Heterocedasticidade: natureza do problema, conseqüências, diagnóstico (testes White, Park, Goldfeld-Quandt e Glejser) e correção (método de mínimos quadrados ponderados e estimadores de variância White).

## Processo de Avaliação
*   Provas intermediárias: duas avaliações de 25 pontos cada.
*   Práticas em sala de aula (exercícios, trabalhos individuais e em grupo): 20 pontos
*   Avaliação global: 30 pontos
*   Reavaliação (substitui a Avaliação Global de 30 pontos e é facultada apenas para os alunos que, após tal avaliação, estivem entre 30 e 59 pontos, abordando todo o conteúdo do semestre).

## Observações
**Justificativa das bibliografias escolhidas:**

**Bibliografia Básica:**

*   O livro Econometria Básica de Damor Gujarati é um clássico no estudo da econometria, sendo amplamente utilizado internacionalmente. O livro possui uma linguagem adequada aos alunos de graduação em Economia, apresentando os principais tópicos em econometria. Além do material contido nos capítulos, os apêndices contidos no livro provê uma excelente revisão de estatística e de álgebra matricial.
*   O livro Econometria na prática dos autores Malbouisson e Tiryaki possui uma linguagem extremamente didática e de fácil entendimento para alunos de graduação, apresentando várias análises práticas dos conteúdos apresentados.
*   Introdução à Econometria do Jeffrey M. Wooldridge é outro clássico mundialmente utilizado no estudo da econometria nos cursos de graduação. O foco principal da obra está em entender e analisar as hipóteses por meio de aplicações empíricas reais.
*   A revista Econometrica publica artigos abrangendo diversos ramos da economia - teórica e empírica, abstrata e aplicada. Ela explora uma gama única de tópicos a cada ano - da fronteira de desenvolvimentos teóricos em muitas áreas novas e importantes, à pesquisa sobre problemas econômicos atuais e aplicados, a estudos metodologicamente inovadores, teóricos e aplicados em econometria.

**Bibliografia Complementar:**

*   O livro Estatística e Introdução a Econometria de Alexandre Sartoris apresenta de forma simples e didática os conceitos de estatística necessários na análise econométrica.
*   O livro Introdução à econometria do Luiz Rogério Alves dos Santos introduz os fundamentos da econometria de forma prática por meio de exemplos da vida real, sem recorrer a cálculos matemáticos ou estatísticos complexos, apresentando os fundamentos e as técnicas estatísticas avançadas mais importantes que economistas e cientistas sociais utilizam para conduzir pesquisas empíricas mais usuais.
*   Econometric Theory é um periódico que além de artigos que incorporam pesquisa teórica original, publica resenhas periódicas de livros, estudos históricos sobre a evolução do pensamento econométrico e sobre seus principais acadêmicos.
*   O livro Econometria Aplicada dos autores Paula Pereda e Denisard Alves aborda métodos para se estimar relações econômicas e discute a identificação de efeitos causais entre variáveis econômicas utilizando dados brasileiros.
*   Econometria dos renomados autores James H. Stock e Mark W. Watson apresenta questões do cotidiano e dados de experimentos empíricos reais, destacando a relevância da econometria em diferentes análises.
*   Econometria de séries temporais do Rodrigo De Losso da Silveira Bueno apresenta métodos de séries temporais, como cointegração, modelos VAR e volatilidade, útil para pesquisas em finanças e macroeconomia.

## Descrição da Bibliografia Básica
*   ECONOMETRICA. Evanston: Econometric Society, Departament of Economics ,1933-. Bimestral. ISSN 1468-0262 versão on-line. Disponível em: https://onlinelibrary-wiley.ez93.periodicos.capes.gov.br/journal/14680262. Acesso em: 16 out. 2020.
*   GUJARATI, Damodar N.; PORTER, Dawn C.. Econometria básica. 5. ed. Porto Alegre, RS: AMGH, 2011. *E-book*. ISBN 9788580550511.
*   MALBOUISSON, Cláudia; TIRYAKI, Gisele Ferreira (org.). Econometria na prática. Rio de Janeiro, RJ: Alta Books, 2017. *E-book*. ISBN 9786555201703.
*   WOOLDRIDGE, Jeffrey M.. Introdução à econometria: uma abordagem moderna. 7. ed. São Paulo, SP: Cengage Learning, 2023. *E-book*. ISBN 9786555584530.

## Descrição da Bibliografia Complementar
*   BUENO, Rodrigo de Losso da Silveira. Econometria de séries temporais. 2. ed., rev. e ampl. São Paulo, SP: Cengage Learning, 2012. *E-book*. ISBN 9788522128259.
*   ECONOMETRIC THEORY. Cambridge: Cambridge University Press ,1985-. bimestral. ISSN 1469-4360 versão on-line. Disponível em: https://www-cambridge.ez93.periodicos.capes.gov.br/core/journals/econometric-theory/all-issues. Acesso em: 16 out. 2020.
*   PEREDA, Paula Carvalho; ALVES, Denisard. Econometria aplicada. Rio de Janeiro, RJ: Elsevier, 2018. *E-book*. ISBN 9788595156012.
*   SANTOS, Luiz Rogério Alves dos. Introdução à econometria. Curitiba, PR: Intersaberes, 2019. *E-book*. ISBN 9788522700974.
*   SARTORIS, Alexandre. Estatística e introdução à econometria. 2. ed. São Paulo, SP: Saraiva, 2013. *E-book*. ISBN 9788502199835.
*   STOCK, James H.; WATSON, Mark W.. Econometria. São Paulo, SP: Pearson, 2004. *E-book*. ISBN 8588639149.
