---
title: "ASPECTOS LEGAIS DA GESTÃO PÚBLICA B"
subtitle: "Período: 2"
description: "Disciplina em andamento na UFMG como parte do currículo de Gestao Publica, sob a orientação do(a) professor(a) Lucas Gelape (Doutorado)."
categories: ["UFMG", "Gestao Publica", "Direito e Regulação"]
carga_horaria: 60
periodo: 2
toc: true
---

## Ementa
Estado, Governo e Administração Pública: administração pública direta e indireta, autarquias, fundações, associações e consórcios públicos, empresas estatais. Princípios básicos da Administração Pública. Administração pública e burocracia. Poderes Administrativos. Atos administrativos. Licitação e Contratos Administrativos. Serviços Públicos. Controle da Administração Pública. Improbidade Administrativa.

## Descrição da Bibliografia Básica
*   AMORIM, Simone; BOULLOSA, Rosana F. O estudo dos instrumentos de políticas públicas: uma agenda em aberto para experiências de migração em escala. Amazônia, Organizações e Sustentabilidade, vol. 2, n. 1, 2013. http://www.spell.org.br/documentos/ver/15446/o-estudo-dosinstrumentos-de-politicas-publicas---
*   BARBOSA, Dayse Vieira Santos; BARBOSA, Nelson Bezerra and NAJBERG, Estela. Regulação em Saúde: desafios à governança do SUS. Cad. saúde colet., Mar 2016, vol.24, no.1, p.49-54. https://www.scielo.br/pdf/cadsc/v24n1/1414-462X-cadsc-1414-462X201600010106.pdf
*   BRASIL. Guia Prático de Governança. Brasília: Presidência da República, 2018. https://www.gov.br/casacivil/pt-br/centrais-de-conteudo/downloads/guia-da-politica-degovernanca-publica
*   BRASIL. Lei 8112 de 1990 Anotada. Ministério do Planejamento, Orçamento e Gestão, 2017. https://www.gov.br/servidor/pt-br/acesso-a-informacao/gestao-de-pessoas/lei-8112-anotada/Lein8.112de1990AnotadaTtulosIeII17.05.2017.pdf
*   CAVALCANTE, Pedro, et al. Inovação no Setor Público. Brasília: ENAP/IPEA, 2017. Capítulos 1 e 2. https://repositorio.enap.gov.br/bitstream/1/2989/1/171002_inovacao_no_setor_publico.pdf
*   CAVALCANTE, Pedro; LOTTA, Gabriela; OLIVEIRA, Vanessa Elias de. Do insulamento burocrático à governança democrática: as transformações institucionais e a burocracia no Brasil. In: Pires, Roberto (org.). Burocracia e políticas públicas no Brasil: interseções analíticas. Brasília: IPEA, 2018. https://www.ipea.gov.br/portal/images/stories/PDFs/livros/livros/180705_livro_burocracia_e_politicas_publicas_no_brasil_cap02.pdf
*   CUNHA, Bruno Q.; KARAM, Ricardo. Regulação estatal no Brasil: o desafio da polimorfia e da complementaridade institucional. Boletim de Análise Político-Institucional, IPEA, n 12, 2017. http://repositorio.ipea.gov.br/bitstream/11058/8100/1/BAPI_n12_Regula%c3%a7%c3%a3o.pdf
*   FERNANDEZ, Rodrigo N. et. al. Parcerias Público-Privadas: uma alternativa para a educação. Planejamento e Políticas Públicas, n 52, 2019. http://repositorio.ipea.gov.br/bitstream/11058/9767/1/ppp_n52_parceria.pdf
*   FILGUEIRAS, Fernando. Indo além do gerencial: a agenda da governança democrática e a mudança silenciada no Brasil. Rev. Adm. Pública, Jan 2018, vol.52, no.1, p.71-88. https://www.scielo.br/pdf/rap/v52n1/1982-3134-rap-52-01-71.pdf
*   FILGUEIRAS, Fernando. Burocracias do controle e controle das burocracias. In: Pires, Roberto (org.). Burocracia e políticas públicas no Brasil: interseções analíticas. Brasília: IPEA, 2018. https://www.ipea.gov.br/portal/images/stories/PDFs/livros/livros/180705_livro_burocracia_e_politicas_publicas_no_brasil_cap14.pdf
*   GOVERNO FEDERAL. Diretrizes Gerais e Guia Orientativo para Elaboração de Análise de Impacto Regulatório. Brasília: Presidência da República, 2018. https://www.gov.br/casacivil/pt-br/centrais-de-conteudo/downloads/diretrizes-gerais-e-guia-orientativo_final_27-09-2018.pdf/view
*   JUSTEN FILHO, Marçal. Art. 20 da LINDB - Dever de transparência, concretude e proporcionalidade nas decisões públicas. Revista Direito Administrativo, nº especial, 2018. http://bibliotecadigital.fgv.br/ojs/index.php/rda/article/view/77648/74311
*   MARQUES, Eduardo Cesar. Redes sociais e poder no Estado brasileiro: aprendizados a partir de políticas urbanas. Rev. bras. Ci. Soc., Fev 2006, vol.21, no.60, p.15-41. https://www.scielo.br/pdf/rbcsoc/v21n60/29759.pdf
*   OLLAIK, Leila Giandoni, & MEDEIROS, Janann Joslin. (2011). Instrumentos governamentais: reflexões para uma agenda de pesquisas sobre implementação de políticas públicas no Brasil. Revista de Administração Pública, 45(6), 1943-1967. https://www.scielo.br/pdf/rap/v45n6/a15v45n6.pdf
*   PECI, Alketa, PIERANTI, Octavio Penna and RODRIGUES, Silvia. Governança e new public management: convergências e contradições no contexto brasileiro. Organ. Soc., Set 2008, vol.15, no.46, p.39-55. https://www.scielo.br/pdf/osoc/v15n46/02.pdf
*   PIO, Carlos. A estabilização heterodoxa no brasil: idéias e redes políticas. Rev. bras. Ci. Soc., Jun 2001, vol.16, no.46, p.31-54. https://www.scielo.br/pdf/rbcsoc/v16n46/a02v1646.pdf
*   PEREIRA, Alvaro Luis dos Santos and PALLADINI, Gabriel Maldonado. Parceria público-privada para construção de moradia popular: fundamentos institucionais para a expansão do mercado de habitação em São Paulo. Cad. Metrop., Dez 2018, vol.20, no.43, p.879-903. https://www.scielo.br/pdf/cm/v20n43/2236-9996-cm-20-43-0879.pdf
*   PEREIRA, Ricardo A. de Castro and FERREIRA, Pedro Cavalcanti. Efeitos de Crescimento e Bem-estar da Lei de Parceria Público-Privada no Brasil. Rev. Bras. Econ., Jun 2008, vol.62, no.2, p.207-219. https://www.scielo.br/pdf/rbe/v62n2/05.pdf
*   RIZARDI, Bruno; VICENTE, Tomaz. Design ágil para inovação social e desenvolvimento. Brasília: PNUD/ENAP, 2020. https://repositorio.enap.gov.br/bitstream/1/5647/1/Design%20A%cc%81gil%20para%20Inovac%cc%a7a%cc%83o%20Social%20e%20Desenvolvimento_PNUD%20e%20ENAP_Completo.pdf
*   SANTOS, Thadeu Borges Souza et al. Gestão indireta na atenção hospitalar: análise da contratualização por publicização para rede própria do SUS. Saúde debate, Out 2018, vol.42, no. spe2, p.247-261. https://www.scielo.br/pdf/sdeb/v42nspe2/0103-1104-sdeb-42-spe02-0247.pdf
*   SOUZA, Regina Luna S. Contratos de gestão na administração pública federal. CLAD, 2012. https://repositorio.enap.gov.br/bitstream/1/1245/1/souzareg.pdf
*   THAMER, Rogério and LAZZARINI, Sérgio Giovanetti. Projetos de parceria público-privada: fatores que influenciam o avanço dessas iniciativas. Rev. Adm. Pública, Ago 2015, vol. 49, no. 4, p.819-846. https://www.scielo.br/pdf/rap/v49n4/0034-7612-rap-49-04-00819.pdf
*   WELTER, Larissa M.; ENSSLIN, Sandra R. Consequências não intencionais do Sistema de Avaliação de Desempenho. 10º CONGRESSO DE CONTABILIDADE E FINANÇAS, Florianópolis, 2020. http://dvl.ccn.ufsc.br/10congresso/anais/10CCF/20200716143556_id.pdf

## Descrição da Bibliografia Complementar
*   ARANTES, Rogério Bastos et. al. Controles democráticos sobre a administração pública no Brasil: Legislativo, tribunais de contas, Judiciário e Ministério Público. In: LOUREIRO, Maria Rita, ABRUCIO, Luiz Fernando & PACHECO, Regina Silva (Org.). Burocracia e política no Brasil: desafios para o estado democrático no século XXI. Rio de Janeiro: Editora FGV, 2010. p. 109 a 147.
*   AVRITZER, Leonardo; COSTA, Sérgio. Teoria crítica, democracia e esfera pública: concepções e usos na América Latina. Dados – Revista de Ciências Sociais, vol. 47, nº 4, 2004. p. 703-728.
*   BOBBIO, Norberto. Democracia: os fundamentos. In: Teoria Geral da Política. Rio de Janeiro: Campus, 2000.
*   CUNHA, Eleonora. “A reinvenção do Estado brasileiro: a criação de instituições que articulam participação e deliberação”. Efetividade Deliberativa: estudo comparado de Conselhos Municipais de Assistência Social (1997 / 2006). Tese de Doutorado em Ciência Política, UFMG, 2009, p. 61-74.
*   MATIAS-PEREIRA, José. Curso de Administração Pública. São Paulo: Atlas, 2009.
*   PEREIRA, Luiz Carlos Bresser. As duas fases da história e as fases do capitalismo. Escola de Economia de São Paulo da Fundação Getúlio Vargas FGV-EESP. Texto para discussão n. 278, Maio de 2011.
*   WEBER, Max. A política como vocação. In: C. Wright Mills e H. H. Gerth (Eds.). Ensaios de Sociologia. Rio de Janeiro: LTC, 2002
