---
title: "METODOLOGIA"
subtitle: "Nota: 85 | Período: 1"
description: "Disciplina cursada na UFMG como parte do currículo de Gestao Publica, sob a orientação do professor(a) Claudia Feres Faria (Doutorado)."
categories: ["UFMG", "Academico", "Gestao Publica"]
carga_horaria: 60
nota: 85
periodo: 1
toc: true
---

## Ementa
Noções gerais de filosofia da ciência. Elementos básicos de metodologias qualitativa e quantitativa. Noções básicas de metodologia científica para a Gestão Pública. Elaboração de trabalhos científicos. Familiarização com indicadores relevantes para a Gestão Pública: propriedades, características e uso em políticas públicas.

## Descrição da Bibliografia Básica
*   CASTRO, Cláudio de Moura, A Pratica da Pesquisa, São Paulo, 2ª Ed., 2006.
*   DEMO, Pedro Metodologia Científica em Ciências Socais, São Paulo, Ed. Atlas, 1992. Caps 3 e 4.
*   DEMO, Pedro. Metodologia Científica. Vídeo. Disponível em: https://www.youtube.com./watch?v=hqko1p-3aeQ
*   ECCO, Humberto Como se faz uma tese em ciências humanas, São Paulo, Ed. Perspectiva, 2010.
*   FRANÇA, J. L. & VASCONCELLOS, A. C. Manual para normalização de publicações técnico-científicas, Ed. UFMG, 9ª Edição, 2014
*   LAVILLE, C.; DIONNE, J. A construção do saber: Manual de metodologia da pesquisa em Ciências Humanas, Ed. UFMG, ARTMED, 2007. Caps. 1, 2, 3, 6, 7, 9 e 10, Anexo Teste de Hipóteses Estatísticas.
*   KUHN, Thomas S. A estrutura das revoluções científicas, São Paulo Editora Perspectiva, 1994. Caps 9.

## Descrição da Bibliografia Complementar
*   ABNT – Associação Brasileira de Normas Técnicas.
*   DEMO, Pedro Metodologia Científica em Ciências Sociais, São Paulo, Ed. Atlas, 1992. Cap.4.
