---
title: "EMPREENDEDORISMO E INOVAÇÃO"
subtitle: "Nota: 77 | Extracurricular"
description: "Disciplina cursada na PUC Minas como parte do currículo de Administracao, sob a orientação do professor(a) Osvaldo Maurício de Oliveira (Mestrado)."
categories: ["PUC Minas", "Gestao", "Administracao"]
carga_horaria: 80
nota: 77
periodo: 100
toc: true
---

## Ementa
Empreendedorismo: conceitos e definições e Modalidades (corporate venturing, intrapreneurship; Negócios e Social). O Perfil e as características do empreendedor. As habilidade e competências necessárias aos empreendedores. A Importância do Empreendedorismo para uma sociedade. A identificação das oportunidades de negócios. A criação de novas empresas. Os tipos de Negócios. O processo de empreender. O ambiente de negócios. Noções de modelagem de negócios. Conceitos de inovação (cultura e processos); tipos (incremental e de tuptura) e impactos nas atividades empresariais e na economia. Modelos de gestão da inovação. Impactos estratégicos da inovação no desempenho das organizações e sua aplicação no mundo corporativo. Tópicos emergentes em empreendedoriso e inovação.

## Objetivos
- Compreender o papel e a importância do empreendedorismo no desenvolvimento sustentável da sociedade bem como desenvolver habilidades e competências para identificar oportunidades de mercado e criação de projetos e negócios inovadores.

### Objetivos Específicos:
- Compreender as diversas fases do processo empreendedorismo sustentável (econômico, social, ambiental e cultural);
- Reconhecer o empreendedorismo como uma possibilidade de escolha profissional;
- Conhecer e utilizar as tecnologias contemporâneas de desenvolvimento de negócios;
- Entender o empreendedorismo endógeno como fonte de inovação empresarial;

## Métodos Didáticos
Vídeo aulas, estudo de casos, aplicação de ferramentas do Design Thinking; Oficinas de empreendedorismo com aplicação de ferramentas digitais de Persona e modelagem de negócio.

## Unidades de Ensino
1.  **O processo empreendedor: conceitos fundamentais**
    1.1 Introdução ao empreendedorismo: conceitos e escolas do empreendedorismo;
    1.2 Modalidades de empreendedorismo (corporate venturing, intrapreneurship; empreendedor de negócios e social).
    1.3 A Importância do Empreendedorismo sustentável para uma sociedade (Econômica, Social e Ambiental).
    1.4 O Perfil e as características do empreendedor. Soft skills - habilidades e competências do empreendedor.

2.  **Ecossistema de empreendedorismo e Inovação, Análise de Cenários e de oportunidades de mercado.**
    2.1 Conceitos de Inovação (cultura e processos); tipos de inovação (incremental e de ruptura);
    2.2 Impactos das inovações tecnológicas nas estratégias corporativas como vantagem competitiva;
    2.3 A indústria 5.0, empreendedorismo 5.0 e as oportunidades do mundo digital;
    2.4 A criação de novas empresas, tipos de Negócios e ambiente de negócios.
    2.5. Modelos de gestão da inovação.
    2.6 Business Model Canvas (BMC) - Startup Enxuta, Spin-off;
    2.7 Mecanismo de estímulo à startups;
    2.8 Eventos de fomento a startups;
    2.9 Tipos de investidores e financiadores de startups;

3.  **Processo de Ideação de Negócios**
    3.1 Processo de criação e ideação de negócios, identificação de Dor de mercado;
    3.2 Construção do Mapa de empatia, Persona e Pesquisa de mercado;
    3.3 Noções de Modelagem de negócio construção do Business Model Canvas - BMC.
    3.4 Análise e validação da ideia;
    3.5 Prototipagem da solução, Mínimo Produto Viável MVP.

4.  **Plano de desenvolvimento do projeto de negócio**
    4.1. Planejamento da implementação do negócio - (cronograma Roadmap);
    4.2 Identificação de editais para apresentação do projeto.
    4.3 Preparação e realização de Pitch da proposta de negócio;
    4.4 Abordagem de tópicos emergentes em empreendedorismo e inovação.

## Processo de Avaliação
*   Atividades avaliativas de conteúdo - 55 pontos
*   Atividade Prática (projeto) - 45 pontos
*   Reavaliação 100 pontos

## Descrição da Bibliografia Básica
*   CADERNOS DE GESTÃO E EMPREENDEDORISMO. Rio de Janeiro, RJ: Universidade Federal Fluminense ,2013-. Quadrimestral (4 em 4 meses). ISSN 2318-9231. Disponível em: http://periodicos.uff.br/cge. Acesso em: 10 set. 2018.
*   DEGEN, Ronald Jean. O Empreendedor: fundamentos da iniciativa empresarial - 8ª edição. Editora Pearson 384 ISBN 9788534602174.
*   DORNELAS, José Carlos Assis (Coord.). Plano de negócios com o modelo Canvas: guia prático de avaliação de ideias de negócio a partir de exemplos. Rio de Janeiro, RJ: LTC, 2015. E-book ISBN 978-85-216-2965-8.
*   SERTEK, Paulo. Empreendedorismo. Curitiba: Intersaberes, 2012. *E-book*. ISBN 9788565704199.

## Descrição da Bibliografia Complementar
*   AMARAL, Daniel Capaldo *et al.* Gerenciamento ágil de projetos: aplicação em produtos inovadores. São Paulo: Saraiva, 2011. *E-book*. ISBN 9788502122291.
*   DOLABELA, Fernando. Oficina do empreendedor. São Paulo: Cultura, c1999. 275 p. ISBN 8529300483., Nº de Exemplares: 6.
*   FREITAS FILHO, Fernando Luiz. Gestão da inovação: teoria e prática para implantação. São Paulo: Atlas, 2013. *E-book*. ISBN 9788522480661.
*   HISRICH, Robert D.; PETERS, Michael; SHEPHERD, Dean A.. Empreendedorismo. 9. ed. Porto Alegre: AMGH, 2014. *E-book*. ISBN 9788580553338.
*   REVISTA DE EMPREENDEDORISMO E GESTÃO DE PEQUENAS EMPRESAS . São Paulo, SP: ANEGEPE , Quadrimestral (4 em 4 meses). ISSN 2316-2058. Disponível em: http://www.regepe.org.br/regepe/index. Acesso em: 10 set. 2018.
*   TEIXEIRA, Tarcisio; LOPES, Alan Moreira (coord.). Startups e inovação: direito no empreendedorismo (entrepreneurship law). 2. ed. Barueri, SP: Manole, 2020. *E-book*. ISBN 9788520461976.
