---
title: "MICROECONOMIA"
subtitle: "Nota: 66 | Período: 2"
description: "Disciplina cursada na PUC Minas como parte do currículo de Economia, sob a orientação do professor(a) Flavio Constantino Barbosa (Mestrado)."
categories: ["PUC Minas", "Microeconomia", "Economia"]
carga_horaria: 40
nota: 66
periodo: 2
toc: true
---

## Ementa
Teoria de comportamento do consumidor e da demanda. Escolha envolvendo risco. Teoria da firma: fatores de produção e produto; Função de produção; produtividade média e marginal; rendimentos marginais e de escala.

## Objetivos
Desenvolver as principais análises de tomada de decisão econômica, com o foco nos comportamentos do consumidor e do produtor, dentro de uma abordagem teórico/prática.

**Objetivos Específicos:**
*   Aprofundar o conhecimento e a discussão em todos os aspectos que envolvem comportamento racional em um ambiente de escassez;
*   Evidenciar a importância da compreensão da análise de custo e benefício;
*   Aprofundar os conhecimentos e a prática das diversas ferramentas matemáticas para a análise do comportamento econômico.

## Métodos Didáticos
Aulas expositivas, vídeos e seminários.

## Unidades de Ensino
1.  **Nivelamento:** princípios de economia básicos e conceitos matemáticos
2.  **Teoria do consumidor**
    2.1. O processo de decisão
    2.2. Restrição orçamentária
    2.3. Preferências
    2.4. Função de utilidade
    2.5. Equilíbrio gráfico do consumidor
    2.6. Equilíbrio matemático do consumidor
    2.7. Demanda
    2.8. Efeito renda e substituição
3.  **Escolha e incerteza**
    3.1. Descrevendo o risco
    3.2. Preferências em relação ao risco
    3.3. Reduzido o risco
    3.4. - Economia Comportamental
4.  **Teoria da Firma**
    4.1. Comportamento da firma
    4.2. Tecnologia
    4.3. Função de Produção

## Processo de Avaliação
*   3 provas no valor de 30 pontos.
*   1 trabalho em grupo no valor de 10 pontos.
*   Exame especial no valor de 30 pontos.

## Descrição da Bibliografia Básica
*   MANKIW, N. Gregory. Princípios de microeconomia. 4. ed. São Paulo: Cengage Learning, c2022. *E-book*. ISBN 9786555584158.
*   PINDYCK, Robert S.; Rubinfeld, Daniel L. Microeconomia - 7ª edição. Editora Pearson 676 ISBN 9788576052142.
*   REVISTA BRASILEIRA DE ECONOMIA DE EMPRESAS. Brasília: UCB, Pró-Reitoria de Pós-Graduação e Pesquisa, 2001-. Quadrimestral. ISSN 2236-9775 versão on-line. Disponível em: https://portalrevistas.ucb.br/index.php/rbee/index. Acesso em: 21 ago. 2018.
*   VARIAN, Hal R.; MACEDO, Regina Coeli Moura de. Microeconomia: uma abordagem moderna. 9. ed. Rio de Janeiro: Elsevier, c2015. *E-book*. ISBN 9788595155107.

## Descrição da Bibliografia Complementar
*   COUTINHO, Luciano G.; FERRAZ, João Carlos. Estudo da competitividade da indústria brasileira. 4. ed. São Paulo: Editora da UNICAMP, 2002. 510p. ISBN 8530802977, Nº de Exemplares: 2.
*   ECONOMIA APLICADA. São Paulo: USP, Departamento de Economia ,1997-. Trimestral. ISSN 1980-5330 versão on-line. Disponível em: http://www.revistas.usp.br/ecoa. Acesso em: 1 jul. 2020.
*   FRANK, Robert H. Princípios de economia. 4. Porto Alegre AMGH 2012 ISBN 9788580550979.
*   KAHNEMAN, Daniel. Rápido e devagar: duas formas de pensar. Rio de Janeiro: Objetiva, 2012. 606 p. ISBN 9788539003839 (broch.)., Nº de Exemplares: 1.
*   LEVITT, Steven D.; DUBNER, Stephen J.; LYRA, Regina. Freakonomics: o lado oculto e inesperado de tudo que nos afeta. 12. ed. Rio de Janeiro: Campus, 2005. 254 p. ISBN 8535215042., Nº de Exemplares: 1.
*   PORTER, Michael E.. A vantagem competitiva das nações. Rio de Janeiro: Campus, 1993. 897 p. ISBN 8570017588 (broch.)., Nº de Exemplares: 2.
