---
title: "ECONOMIA FINANCEIRA: OPERAÇÕES E ESTRUTURA"
subtitle: "Período: 3 | Nota: 95"
description: "Disciplina cursada na PUC Minas como parte do currículo de Economia, sob a orientação do(a) professor(a) Frederico Sande Viana (Mestrado)."
categories: ["PUC Minas", "Economia", "Finanças e Contabilidade"]
carga_horaria: 80
nota: 95
periodo: 3
toc: true
---

## Ementa
Matemática financeira; Taxas de juros; Produtos do mercado econômico-financeiro; Estrutura das taxas de juros; Estrutura temporal das taxas de juros; Mercados futuros e a estrutura temporal das taxas de juros; Carregamento de ativos; Duration e convexidade. Atividades de integração entre conhecimentos acadêmicos e saberes de outros setores da sociedade, unindo teoria e prática, por meio das modalidades de extensão.

## Objetivos
Compreender as operações e estruturas financeiras no Brasil requer um domínio por completo do cálculo financeiro. A dinâmica da taxa de juros e da inflação, e as inúmeras operações financeiras e produtos bancários, além de produtos ligados a meios de pagamentos e ao consumo varejista exigem dos profissionais de bancos e empresas conhecimentos amplos sobre esses temas.

## Métodos Didáticos
Aulas expositivas com resolução de exercícios. Serão propostos ao longo do curso exercícios avaliativos. Atividade de extensão desenvolvida pelos alunos com acompanhamento do professor.

## Unidades de Ensino
**0) Nivelamento:**
1. Juros Simples e Compostos: Entender como os juros são calculados e como afetam o valor de investimentos.
2. Taxas de Retorno: Compreender como calcular e interpretar taxas de retorno de investimentos.
3. Valor Presente e Futuro: Aprender a calcular o valor presente e futuro de investimentos, considerando juros e taxas de retorno.

**1) Matemática financeira:**
1.1 Capital;
1.2 Fluxo de caixa;
1.3 Juros;
1.4 Taxa de juros;
1.5 Regimes de capitalização;
1.6 Séries uniformes de pagamentos;
1.7 Métodos de avaliação de investimentos.

**2) Taxas de juros:**
2.1 Taxas proporcionais;
2.2 Taxas equivalentes;
2.3 Taxa nominal versus taxa efetiva;
2.4 A taxa over anual do mercado brasileiro a partir de 1998;
2.5 Taxas variáveis ou flutuantes;
2.6 Taxa acumulada;
2.7 Taxa média;
2.8 Taxa real.

**3) Produtos do mercado financeiro:**
3.1 Títulos de captação bancária;
3.2 Títulos de crédito;
3.3 Títulos imobiliários;
3.4 Títulos agrícolas;
3.5 Modalidades de financiamento.

**4) Estrutura das taxas de juros:**
4.1 Os principais mercados de taxas de juros;
4.2 Estrutura das taxas de juros em relação a doadores e tomadores de recursos;
4.3 Estrutura das taxas de juros em relação à cobertura de riscos Formação do spread.

**5) Estrutura temporal das taxas de juros:**
5.1 Exemplos: Brasil e EUA;
5.2 Informações para a elaboração da estrutura temporal das taxas de juros.

**6) Mercados futuros e a estrutura temporal das taxas de juros:**
6.1 A existência natural dos mercados futuros;
6.2 Os contratos de DI futuro na BM&FBOVESPA;
6.3 Informações obtidas a partir dos contratos de DI futuro da BM&FBOVESPA.

**7) Carregamento de ativos:**
7.1 Carregamento de ativos;
7.2 Elementos de um carregamento de títulos;
7.3 Carregamento da tesouraria;
7.4 Carregamento de títulos e valor de um título a mercado.

**8) Duration e convexidade:**
8.1 Conceito de prazo médio;
8.2 Duration;
8.3 Aplicações da duration;
8.4 Estudo da variação do preço dos títulos em função das variações das taxas de juros do mercado;
8.5 Sensibilidade do valor da carteira em relação à estrutura temporal da taxa de juros.

## Processo de Avaliação
Nossas atividades, como exercícios avaliativos e provas serão todas on-line realizadas pelo Canvas.
Os exercícios avaliativos serão semanais e sempre disponibilizados com base na matéria (vídeos) já vistos até a semana anterior e terão 4 dias corridos para serem realizados. Poderão ser feitas 2 tentativas, sendo que vale sempre a última tentativa, ou seja, se fizer uma segunda tentativa terá que marcar todas as questões novamente. Não haverá reposição dos exercícios avaliativos sendo importante respeitar o prazo de 4 dias corridos para a sua realização.
Será realizada uma prova no final do semestre e também haverá uma prova de recuperação para os alunos que não atingiram 60 pontos no final do semestre. As provas serão realizadas aos sábados preferencialmente) no turno da tarde, de 14:00 às 19:00 hs, sendo que o aluno ao abrir a prova no Canvas terá que concluí-la.

**Distribuição de pontos (100 pontos):**
*   Exercícios avaliativos semanais e trabalhos: 50 pontos;
*   Atividade de Extensão: 20 pontos;
*   Prova Final: 30 pontos.

**Prova de recuperação (100 pontos):** nesse caso soma-se a nota do aluno no final do semestre com a nota da prova de recuperação de divide-se por 2, sento essa a nota final do aluno. Será aprovado o aluno que tiver pelo menos 60 pontos.

## Observações
**Atividade de Extensão:** Será desenvolvida através de grupos de alunos um trabalho que estabeleça uma relação do curso com a sociedade.

**Justificativa dos Livros da Bibliografia:**

*   RACE: revista de administração, contabilidade e economia. *Justificativa: Visa publicar artigos que aprofundem teorias, métodos e/ou práticas de gestão. Busca ainda promover a convergência e disseminação de conhecimentos sobre sustentabilidade abrigando estudos relacionados à Administração, à Contabilidade e à Economia.*
*   SAMANÉZ, Carlos Patrício. Matemática financeira. 5. ed. São Paulo: Pearson Prentice Hall, 2010. *Justificativa: O livro é um clássico da área de Cálculo Financeiro. Ensina os cálculos por meio de exemplos.*
*   ASSAF NETO, Alexandre. Matemática financeira e suas aplicações. 15. ed. Barueri, SP: Atlas, 2022. *Justificativa: O livro foi escrito com o intuito não somente de cobrir os fundamentos teóricos da Matemática Financeira, como também de desenvolver suas principais aplicações práticas. As extensas aplicações da matéria são processadas de forma a adaptar o conhecimento teórico a uma situação prática, não havendo preocupações maiores com relação aos detalhes normativos da operação, bastante mutáveis em nossa economia.*
*   SECURATO, José Roberto (org.). Cálculo financeiro das tesourarias: bancos e empresas. 5. ed. São Paulo, SP: Saint Paul, 2015. *Justificativa: A sofisticação das operações e estruturas financeiras no Brasil requer um domínio por completo do cálculo financeiro. A dinâmica da taxa de juros e da inflação, e as inúmeras operações financeiras e produtos bancários, além de produtos ligados a meios de pagamentos e ao consumo varejista exigem dos profissionais de bancos e empresas conhecimentos amplos sobre esses temas. Cálculo financeiro das tesourarias aborda a moderna gestão de tesourarias reunindo todos os elementos técnicos necessários para sua boa administração.*
*   REVISTA BRASILEIRA DE FINANÇAS. Rio de Janeiro: Sociedade Brasileira de Finanças ,2003-. 2009-. *Justificativa: A Revista Brasileira de Finanças é a publicação oficial da Sociedade Brasileira de Finanças e tem como objetivo o avanço e a disseminação do conhecimento financeiro no Brasil por meio da publicação de artigos técnicos em todas as áreas de pesquisa em finanças e economia financeira.*
*   VIEIRA SOBRINHO, José Dutra. Matemática financeira. 8. ed. São Paulo: Atlas, c2018. *Justificativa: Livro-texto para a disciplina Matemática Financeira. Leitura complementar para as disciplinas Mercado de Capitais e Elaboração e Análise de Projetos dos cursos de Administração, Ciências Contábeis e Economia.*
*   HAZZAN, Samuel; POMPEO, José Nicolau. Matemática financeira. 7. ed. São Paulo, SP: Saraiva, 2014. *Justificativa: Matemática financeira, dos autores Samuel Hazzan e José Nicolau Pompeo, fornece, de maneira lógica e com encadeamento entre teoria e exercícios, os instrumentos para o cálculo financeiro dentro da realidade brasileira. O livro aborda os conceitos de juros simples e compostos, descontos, análise de pagamentos e investimentos, financiamento em prestações iguais, juros em contexto inflacionário e pagamentos de longo prazo, oferecendo formas de aplicação atualizadas do mercado financeiro brasileiro.*
*   PUCCINI, Abelardo de Lima. Matemática financeira: objetiva e aplicada. 11. ed. São Paulo, SP: Saraiva Uni, 2022. *Justificativa: O livro apresenta os aspectos práticos da matemática financeira por meio de exemplos resolvidos pela calculadora HP-12C e pela planilha eletrônica Excel.*
*   CASTELO BRANCO, Anísio Costa. Matemática financeira aplicada: método algébrico, HP-12C, Microsoft Excel. 4. ed. rev. e ampl. São Paulo, SP: Cengage Learning, c2016. *Justificativa: Mostrar os conceitos da matemática financeira de forma clara é o objetivo desta obra. Com exemplos práticos e metodologia objetiva e de fácil compreensão, o autor apresenta as três principais maneiras de solucionar os exemplos dados, ou seja: a forma algébrica, a calculadora financeira HP-12C e as planilhas eletrônicas Excel.*
*   MELLO, Cleyson de Moraes; ALMEIDA NETO, José Rogério Moura de; PENTAGNA, Regina. Curricularização da extensão universitária: teoria, prática. 2. ed. Rio de Janeiro: Processo, 2022. *Justificativa: Esta obra oferece uma clara e panorâmica visão de como vem sendo realizada a evolução da educação. Os autores apresentam uma personalíssima análise do mais refinado pensamento sobre a Curricularização da Extensão. Os autores, com larga expertise em gestão universitária, abordam, ainda, o planejamento, o registro e a implementação da extensão universitária nas matrizes curriculares.*

## Descrição da Bibliografia Básica
*   ASSAF NETO, Alexandre. Matemática financeira e suas aplicações. 15. ed. Barueri, SP: Atlas, 2022. *E-book*. ISBN 9786559773244.
*   RACE: revista de administração, contabilidade e economia. Joaçaba: UNOESC, Campus de Joaçaba ,2002-. 2006-. ISSN 2179-4936 versão on-line. Disponível em: http://editora.unoesc.edu.br/index.php/race. Acesso em: 10 set. 2018.
*   SAMANÉZ, Carlos Patrício. Matemática financeira. 5. ed. São Paulo: Pearson Prentice Hall, 2010. *E-book*. ISBN 9788576057994.
*   SECURATO, José Roberto (org.). Cálculo financeiro das tesourarias: bancos e empresas. 5. ed. São Paulo, SP: Saint Paul, 2015. *E-book*. ISBN 9788580041569.

## Descrição da Bibliografia Complementar
*   CASTELO BRANCO, Anísio Costa. Matemática financeira aplicada: método algébrico, HP-12C, Microsoft Excel. 4. ed. rev. e ampl. São Paulo, SP: Cengage Learning, c2016. *E-book*. ISBN 9788522122721.
*   HAZZAN, Samuel; POMPEO, José Nicolau. Matemática financeira. 7. ed. São Paulo, SP: Saraiva, 2014. *E-book*. ISBN 9788502618176.
*   MELLO, Cleyson de Moraes; ALMEIDA NETO, José Rogério Moura de; PENTAGNA, Regina. Curricularização da extensão universitária: teoria, prática. 2. ed. Rio de Janeiro: Processo, 2022. *E-book*. ISBN 9786589351955.
*   PUCCINI, Abelardo de Lima. Matemática financeira: objetiva e aplicada. 11. ed. São Paulo, SP: Saraiva Uni, 2022. *E-book*. ISBN 9786587958064.
*   REVISTA BRASILEIRA DE FINANÇAS. Rio de Janeiro: Sociedade Brasileira de Finanças ,2003-. 2009-. ISSN 1984-5146 versão on-line. Disponível em: http://bibliotecadigital.fgv.br/ojs/index.php/rbfin/index. Acesso em: 12 jul. 2018.
*   VIEIRA SOBRINHO, José Dutra. Matemática financeira. 8. ed. São Paulo: Atlas, c2018. *E-book*. ISBN 9788597015461.
