---
title: "INTRODUÇÃO A ECONOMIA"
subtitle: "Nota: 80 | Período: 1"
description: "Disciplina cursada na PUC Minas como parte do currículo de Economia, sob a orientação do professor(a) Marcelo Meira de Jesus (Mestrado)."
categories: ["PUC Minas", "Economia Aplicada", "Economia"]
carga_horaria: 80
nota: 80
periodo: 1
toc: true
---

## Ementa
Noções introdutórias de Ciência Econômica. Fundamentos de Microeconomia: oferta, demanda, equilíbrio e estruturas de mercado. A empresa, a produção e os custos. Fundamentos de Macroeconomia: agregados macroeconômicos. Modelos de determinação da renda. Noções de política fiscal, monetária e cambial.

## Objetivos
**Objetivo Geral:**
Dotar os alunos dos conhecimentos teóricos necessários à compreensão do comportamento do consumidor e da firma, bem como os conceitos macroeconômicos elementares, possibilitando-lhes compreender as decisões de políticas macroeconômicas e os seus impactos no sistema econômico.

**Objetivos Específicos:**
*   Aprofundar o conhecimento e a discussão em todos os aspectos que envolvem comportamento racional em um ambiente de escassez;
*   Evidenciar a importância da compreensão da análise de custo e benefício;
*   Aprofundar os conhecimentos e a prática das diversas ferramentas econômicas para a análise do comportamento humano bem como o resultado agregado.

## Métodos Didáticos
Aulas expositivas, seminários e palestras. Disponibilização de exercícios de fixação e estudos dirigidos.

## Unidades de Ensino
**Unidade I: Nivelamento: princípios de economia**
*   O problema econômico básico
*   Escassez, decisão e incerteza.
*   Curva (fronteira) de Possibilidade de Produção (o conceito de custo de oportunidade).
*   Modelo do fluxo circular da renda

**Unidade II: Fundamentos de Microeconomia**
2.1: Fenômeno de mercado
*   Definições e campo de estudo.
*   Demanda, Oferta e Equilíbrio de Mercado:
    *   Análise da demanda de mercado.
    *   Análise da oferta de mercado.
    *   O equilíbrio de mercado.
    *   Elasticidade-preço da demanda e fatores que afetam a elasticidade-preço da demanda.
    *   Relação entre receita total e elasticidade.
    *   Outros tipos de elasticidade.
2.2: Estruturas de Mercado: diferenças Conceituais.
2.3: Teoria da firma: produção e custos
*   Produção com um fator variável e um fixo: uma análise de curto prazo.
*   Objetivo da empresa
*   Custos explícitos e implícitos
*   Custos a curto prazo.
*   Custos a longo prazo.

**Unidade III: Fundamentos de Macroeconomia**
3.1- Definições e campo de estudo.
3.2- Sistemas econômicos
*   O fluxo circular da atividade econômica.
*   Conceitos básicos: produto, renda e despesa agregados.
*   Os principais agregados macroeconômicos.
*   PIB nominal e PIB real - Noções de números-índices.
3.3 Crescimento econômico
3.4- Ciclos de negócios ou flutuação econômica
*   Determinação do Nível de Renda e Produtos Nacionais: o mercado de bens e serviços
*   Modelo Keynesiano Simples de Determinação da Renda.
3.5- Noções de Política fiscal, monetária e cambial.
*   O setor público, os tributos e os gastos governamentais.
*   Déficit público: conceitos e formas de financiamento.
*   Moeda e instrumentos de política monetária.
*   Taxa de câmbio e regimes cambiais.
*   Balanço de Pagamentos.

## Processo de Avaliação
Seguindo o modelo adotado pela PUC Minas, a distribuição de pontos se dará da seguinte forma:
*   10 pontos, divididos em exercícios de fixação e estudos dirigidos.
*   20 pontos atribuído ao Trabalho Interdisciplinar.
*   40,0 pontos, distribuídos em 02 provas de 20 pontos cada.
*   30,0 pontos, atribuídos à Prova Final.
*   Reavaliação de 30 pontos, em substituição à nota da prova final para alunos que não alcançaram os 60 pontos necessários a aprovação.

## Descrição da Bibliografia Básica
*   MANKIW, N. Gregory. Introdução à economia. 4. São Paulo: Cengage Learning, c2020. E-book. ISBN 9788522127924.
*   PESQUISA E PLANEJAMENTO ECONÔMICO. Rio de Janeiro: Instituto de Planejamento Econômico e Social,1972-. Quadrimestral. ISSN 0100-0551, Nº de Exemplares: 119.
*   TROSTER, Roberto Luis; MOCHÓN MORCILLO, Francisco. Introdução à economia. Ed. rev. e atual. São Paulo: Pearson Education do Brasil, c2002. xxiii, 404p. ISBN 8534610312., Nº de Exemplares: 1.
*   VERSIGNASSI, Alexandre. Crash: uma breve história da economia : da Grécia antiga ao século XXI. 2. ed. atual. São Paulo, SP: Leya, 2015. 351 p. ISBN 978-85-441-0165-0., Nº de Exemplares: 1.

## Descrição da Bibliografia Complementar
*   BOLETIM DE ECONOMIA E POLÍTICA INTERNACIONAL. Brasilia , DF: IPEA/DINTE,2010-. Trimestral (de 3 em 3 meses). ISSN 2176-9915., Nº de Exemplares: 6., Nº de Exemplares: 6.
*   LOPES, Luiz Martins; VASCONCELLOS, Marco Antonio Sandoval de (Org.). Manual de macroeconomia: nível básico e nível intermediário. 3. ed. São Paulo: Atlas, 2008. xvi, 512 p. ISBN 9788522450572., Nº de Exemplares: 10., Nº de Exemplares: 9.
*   LEVITT, Steven D.; DUBNER, Stephen J. Freakonomics: o lado oculto e inesperado de tudo que nos afeta. Ed. rev. e ampl. Rio de Janeiro: Campus, c2005. 333 p. ISBN 9788535227406., Nº de Exemplares: 3.
*   ROSSETTI, José Paschoal. Introdução à economia. 21. ed. Rio de Janeiro: Atlas, 2016. E-book ISBN 9788597008081.
*   VASCONCELLOS, Marco Antonio Sandoval de; ENRIQUEZ GARCIA, Manuel. Fundamentos de economia. 4. ed. São Paulo: Saraiva, 2008. xix, 332 p. ISBN 9788502137257, Nº de Exemplares: 22.
*   VASCONCELLOS, Marco Antonio Sandoval de; OLIVEIRA, Roberto Guena de; BARBIERI, Fabio Augusto. Manual de microeconomia. 3. ed. São Paulo, SP: Atlas, 2011. 1 recurso online ISBN 9788522469932.
