---
title: "IMPACTOS AMBIENTAIS E ALTERAÇÕES CLIMÁTICAS GLOBAIS"
subtitle: "Nota: 80 | Período: 2"
description: "Disciplina cursada na PUC Minas como parte do currículo de Economia, sob a orientação do professor(a) Antoniel Silva Fernandes (Doutorado)."
categories: ["PUC Minas", "Economia Aplicada", "Economia"]
carga_horaria: 80
nota: 80
periodo: 2
toc: true
---

## Ementa
Desenvolvimento Sustentável: definição e análise quali-quantitativa dos usos dos recursos ambientais. Aspectos e Impactos Ambientais. Medidas Mitigadoras: medidas minimizadoras e compensatórias. Processo de licenciamento ambiental: licença prévia, licença de instalação e licença de operação. Estudos Ambientais: EIA/RIMA, RCA e PCA. Instrumentos de compensação e mitigação. Monitoramento e Controle Ambiental. Lei de Crimes Ambientais.

## Objetivos
**Objetivo Geral**
Apresentar os conceitos e métodos referentes a avaliação de impactos e riscos e sua articulação com o processo de licenciamento ambiental bem como a medidas de prevenção, mitigação, controle e compensação ambiental.

**Objetivos Específicos**
**Cognitivos**
*   Reconhecer a extensão e intensidade das modificações impressas pela humanidade no uso e recursEntender o processo de licenciamento ambiental: instâncias, agentes e tipos de licença.
*   Reconhecer as limitações do licenciamento ambiental e da avaliação de impactos e riscos ambientais e sua articulação a outros instrumentos de política pública como o zoneamento ambiental.

**Procedimentais**
*   Distinguir a função e escopo de diferentes estudos ambientais.
*   Distinguir entre medidas de prevenção, contingência, mitigação, controle e compensação de impactos e riscos ambientais.
*   Desenvolver estratégias para elaboração de diagnósticos e avaliação de riscos e de viabilidade ambiental de empreendimentos e projetos.

**Atitudinais**
*   Ser consciente do papel do licenciamento ambiental e da avaliação de impactos e riscos ambientais na gestão dos recursos naturais enquanto instrumentos de política pública.

## Métodos Didáticos
Aulas expositivas para apresentação do conteúdo teórico e utilização de plataformas online; Exercícios avaliativos e de fixação do conteúdo; Leitura dirigida de textos; Análise de Podcasts e filmes.

## Unidades de Ensino
**Unidade 0 - Nivelamento**
Nivelamento de conhecimentos necessários para a Unidade Curricular. Antes do início da cada unidade de ensino, serão revisados os conteúdos de base exigidos para o acompanhamento da disciplina.

*   Bases do ambientalismo;
*   Desenvolvimento sustentável;
*   Valor e Natureza;
*   Antropoceno e o valor invisível da natureza;
*   Conceitos básicos para Avaliação de impacto ambiental (AIA);
*   Histórico da AIA;
*   Quadro legal da AIA;
*   Processo da AIA;
*   AIA no Brasil;
*   Crimes ambientais;
*   Alterações Climáticas.

## Processo de Avaliação
*   Quizes avaliativos somando 100 pontos
*   Reavaliação no valor de 100 pontos:

**ATENÇÃO:** o resultado final de cada aluno corresponderá a soma da nota obtida no semestre regular com a nota obtida na prova da reavaliação, dividida por dois.

## Observações
**Sites relevantes:**
*   http://www.meioambiente.mg.gov.br/images/stories/2019/REGULARIZACAO/SLA/Manual_Exte_SLA_-_1.0.pdf - MANUAL ORIENTATIVO REQUERIMENTO DE LICENÇA AMBIENTAL E ACOMPANHAMENTO DE SOLICITAÇÕES SISTEMA DE LICENCIAMENTO AMBIENTAL - SLA
*   www.mma.gov.br
*   www.ibama.gov.br
*   www.ana.gov.br
*   www.semad.mg.gov.br
*   www.ief.mg.gov.br
*   www.feam.br
*   www.igam.mg.gov.br
*   www.cetesb.sp.gov.br
*   www.abema.org.br
*   www.epa.gov (Agência de Meio Ambiente dos Estados Unidos)
*   www.eea.eu.int (Agência Europeia de Meio Ambiente)
*   www.iaia.org (Organização Internacional de Avaliação de Impactos Ambientais)

## Descrição da Bibliografia Básica
*   LUIS ENRIQUE SÁNCHEZ. Avaliação de impacto ambiental. Editora Oficina de Textos, 2020. 34 p. ISBN 9786586235098.
*   GARCIA, Katia Cristina. Avaliação de impactos ambientais. Editora Intersaberes - 2014 256. ISBN 9788544300916.
*   STEIN, Ronei Tiago. Licenciamento ambiental. Porto Alegre SER - SAGAH 2017 1 recurso online ISBN 9788595022782.

## Descrição da Bibliografia Complementar
*   BARSANO, Paulo Roberto. Legislação ambiental. São Paulo Erica 2019 1 recurso online ISBN 9788536528311.
*   FIORILLO, Celso Antonio Pacheco. Curso de direito ambiental brasileiro. 22. ed. rev., atual e ampl. São Paulo: Saraiva Jur, 2022. *E-book*. ISBN 9786555596748.
*   FOGAÇA, Thiago Kich; TAVEIRA, Bruna Daniela de Araujo; CUBAS, Monyra Guttervill. Conservação dos recursos naturais e sustentabilidade: um enfoque geográfico. Editora Intersaberes - 2017 246. ISBN 9788559723311.
*   REIS, Agnes *et al.* Valoração ambiental de serviços ecossistêmicos. Porto Alegre: SAGAH, 2021. 1 recurso online. ISBN 9786556902395.
*   SOLIMAR GARCIA. A propaganda e sua relação com a sustentabilidade. Editora Blucher 107 ISBN 9788580393774.
