---
title: "PESQUISA EM ECONOMIA"
subtitle: "Nota: 87 | Período: 3"
description: "Disciplina cursada na PUC Minas como parte do currículo de Economia, sob a orientação do professor(a) Júlia Leite de Carvalho Fernandes (Doutorado)."
categories: ["PUC Minas", "Academico", "Economia"]
carga_horaria: 60
nota: 87
periodo: 3
toc: true
---

## Ementa
O pensamento científico: método científico. Pesquisa científica: natureza, modalidades e estrutura de projetos de pesquisa. Trabalhos científicos: natureza, pré-requisitos, tipos e normas técnicas. Diretrizes para leitura, análise, interpretação e redação.

## Carga Externa
A carga horária externa registrada na disciplina compreende o trabalho acadêmico efetivo realizado pelo discente, sob a supervisão do professor, realizado no próprio âmbito da disciplina, na forma de: atividades em biblioteca, iniciação científica, trabalhos individuais e em grupo, práticas de ensino, práticas de extensão, laboratórios, entre outras. Nessa perspectiva, ao professor caberá estabelecer os termos da operacionalização dessas atividades, assim como as necessárias formas de avaliação, no âmbito de suas atividades normais e rotineiras em sala de aula.
(Resolução CNE/CES Nº 3, de 02 de Julho de 2007, art. 2º, item II)

## Objetivos
**Objetivo Geral:**
Este curso pretende oferecer uma abordagem sobre a pesquisa em economia em duas dimensões complementares: uma reflexão introdutória sobre a epistemologia econômica e uma introdução ao processo de elaboração de um projeto de pesquisa e de um trabalho científico, com ênfase para as especificidades de um trabalho monográfico no campo das ciências econômicas.

**Objetivos Específicos:**
*   Introdução ao controverso problema da definição do objeto e do método em economia, oferecendo uma visão de como ocorre a construção do pensamento econômico em suas correntes principais e de sua influência sobre a evolução da economia.
*   Apresentação das etapas de uma investigação científica, notadamente em economia, oferecendo-se uma visão dos métodos e técnicas utilizados em diferentes tipos de pesquisa, além de capacitar o estudante a conceber, elaborar e desenvolver formalmente um projeto.

## Métodos Didáticos
Aulas expositivas, eventuais exibições de vídeos, estudos dirigidos com pesquisa bibliográfica, seguido de debates em sala de aula, seminários, nos quais os estudantes apresentarão os projetos que estão desenvolvendo e os submeterão à apreciação e aos comentários do professor e dos demais colegas.

## Unidades de Ensino
**UNIDADE 0 - Introdução**
*   Definição de Projeto de Pesquisa
*   Estrutura de um Projeto de Pesquisa

**UNIDADE 1. Roteiros de uma investigação científica: a elaboração de um projeto de pesquisa**
1.1. A definição do objeto de investigação
1.2. Como elaborar um projeto de pesquisa os métodos e as técnicas
1.3. Como elaborar um projeto de pesquisa as partes do projeto
2.4. Como elaborar um projeto de pesquisa a redação e a normalização do projeto
2.5. Exemplos comentados de diferentes trabalhos monográficos bem-sucedidosI. Introdução ao problema da definição do objeto e do método em economia

**UNIDADE 2 - Introdução ao problema da definição do objeto e do método em economia**
2.1. O problema do objeto e do método em economia: como a economia se autocompreende. O que é a ciência econômica? O que é o seu objeto? Como os grandes economistas responderam a essas perguntas? Por que razões essas respostas não são incontroversas?
2.2. Visão de conjunto acerca das condições de possibilidade da economia como ciência e de seus campos de atuação

## Processo de Avaliação
**Critérios de Avaliação de Aprendizado**
*   Primeira Prova: 20 pontos
*   Práticas em sala de aula e para realizar-se em casa (exercícios, trabalhos individuais e em grupo): 10 pontos
*   Apresentações Parciais do Projeto Desenvolvido como Produto do Curso: 10 pontos
*   Apresentação Final do Projeto Desenvolvido como Produto do Curso: 30 pontos
*   Prova Final (Avaliação Global): 30 pontos
*   Reavaliação (substitui a AG): 30 pontos

## Observações
**JUSTIFICATIVA DAS BIBLIOGRAFIAS**

**BÁSICA:**

*   BRASILEIRO, Ada Magaly Matias. Como produzir textos acadêmicos e científicos. São Paulo: Contexto, 2021. E-book. ISBN 9786555410051. - *De forma bastante didática e detalhada, o livro discorre por 27 gêneros acadêmico-científicos, como artigo, projeto de pesquisa e relatório. É uma obra pragmática que reúne as especificidades do ambiente acadêmico e, ao mesmo tempo, uma ferramenta de trabalho que não engessa a produção dos autores.*
*   ESTUDOS ECONÔMICOS: [São Paulo]. São Paulo: USP, Instituto de Pesquisas Econômicas ,1971-. *A Revista traz trabalhos inéditos com contribuição original em qualquer área da Economia, comprometendo-se com padrões acadêmicos de excelência e com a pluralidade de ideias, métodos e teorias. O acesso a esse material possibilita aos alunos ter contato com diversas temáticas do campo das Ciências Econômicas e ter exemplificação da escrita acadêmica.*
*   PEREIRA, José Matias. Manual de metodologia da pesquisa científica. 4. ed. rev. e atual. São Paulo: Atlas, 2016. E-book. ISBN 9788597008821. - *Na mesma linha dos demais, esta obra, no entanto, não é voltada especificamente ao economista em formação, mas ao público que deseja introduzir-se na pesquisa acadêmico-científica, independentemente de sua área de origem.*
*   BAPTISTA, Makilim Nunes; CAMPOS, Dinael Corrêa de. Metodologias pesquisa em ciências: análises quantitativa e qualitativa. 2. ed. ampl. e atual. Rio de Janeiro: LTC - Livros Técnicos e Científicos, c2016. E-book. ISBN 9788521630470. - *A obra ensina como fazer o planejamento, a estrutura e execução do trabalho científico; como usar referências e citações; como montar e defender um trabalho de conclusão de curso; dicas para a divulgação dos resultados das pesquisas, além de descrever os principais delineamentos quantitativos e qualitativos, com exemplos de pesquisas em seus capítulos.*
*   BÊRNI, Duílio de Ávila (org.). Técnicas de pesquisa em economia: transformando curiosidade em conhecimento. São Paulo: Saraiva, 2002. xiv, 408 p. ISBN 8502034944. *Obra que oferece um guia completo sobre as técnicas de pesquisa em economia, essencial para a formação de economistas. O livro aborda os principais métodos de pesquisa, desde a formulação de perguntas até a análise de dados, auxiliando os alunos a desenvolverem habilidades de pesquisa e a produzirem trabalhos acadêmicos de alta qualidade.*

**COMPLEMENTAR:**

*   CARVALHO, Maria Cecília Maringoni de (org.). Construindo o saber: metodologia científica, fundamentos e técnicas. Campinas, SP: Papirus, 2021. E-book. ISBN 9786556500928. *A obra aproxima de algumas das questões mais fundamentais na área da metodologia e oferece, também, um instrumento que possa viabilizar a inserção dos alunos no universo da produção científica. Apoiada em dois eixos - um predominantemente teórico e outro de cunho mais prático -, a obra orienta o estudante universitário na realização de trabalhos acadêmicos ou científicos e, ao mesmo tempo, promove, através da metodologia, uma reflexão filosófica mais ampla sobre o homem e o saber científico.*
*   DEMO, Pedro. Praticar ciência: metodologias do conhecimento científico. São Paulo: Saraiva, c2012. E-book. ISBN 9788502148079. *A obra traz a questão da produção de conhecimento próprio como autor enquanto um desafio da sociedade e da economia intensivas de conhecimento. O autor aponta o quanto é imprescindível saber discutir e questionar o conhecimento científico, os métodos e as controvérsias, com atitude crítica e autocrítica.*
*   GIL, Antônio Carlos. Como elaborar projetos de pesquisa. 7. ed. Barueri, SP: Atlas, 2022. E-book. ISBN 9786559771653. - *Trata-se de uma obra bastante conhecida, publicada pela primeira vez em 1988, e que já está em sua quarta edição. Segundo os propósitos anunciados pelo próprio autor, o livro visa a contribuir para a formação de uma postura crítica em relação ao conhecimento econômico e busca ensinar como se desenvolvem as pesquisas econômicas, como nela se obtêm, se interpretam e se apresentam os dados. O livro tenta também considerar a especificidade e a complexidade do objeto e do método da Ciência Econômica, confrontando-os com os das chamadas ciências da natureza. A quase impossibilidade de experimentação e a questão dos valores são características que o autor considera.*
*   MARCONI, Marina de Andrade; LAKATOS, Eva Maria. Fundamentos de metodologia científica: métodos científicos, técnicas de pesquisa, elaboração de referências bibliográficas. 9. ed. atual. São Paulo: Atlas, 2021. E-book. ISBN 9788597026580. - *O trabalho enfatiza a necessidade da precisão dos termos utilizados na constituição dos saberes para a melhor avaliação da aprendizagem e traz aspectos importantes sobre elaboração de trabalhos científicos.*
*   NOVA ECONOMIA. Belo Horizonte: UFMG, Departamento de Ciências Econômicas, 1990-. Semestral. ISSN 1980-5381 versão on-line. - *Publica trabalhos inéditos com contribuição original em qualquer área da Economia, comprometendo-se com padrões acadêmicos de excelência e com a pluralidade de ideias, métodos e teorias. Sua periodicidade é trimestral.*

**Outras indicações:**
*   HEILBRONER, Robert L.. A história do pensamento econômico. *Obra clássica que traz a história do pensamento econômico sendo um grande suporte para que os alunos conheçam os principais pensadores da Economia e seus arranjos teóricos e metodológicos; possibilitando suporte teórico para a construção dos projetos de pesquisa.*

## Descrição da Bibliografia Básica
*   BÊRNI, Duílio de Ávila (org.). Técnicas de pesquisa em economia: transformando curiosidade em conhecimento. São Paulo: Saraiva, 2002. xiv, 408 p. ISBN 8502034944., Nº de Exemplares: 5.
*   BRASILEIRO, Ada Magaly Matias. Como produzir textos acadêmicos e científicos. São Paulo: Contexto, 2021. *E-book*. ISBN 9786555410051.
*   ESTUDOS ECONÔMICOS: [São Paulo]. São Paulo: USP, Instituto de Pesquisas Econômicas ,1971-. out. 2000-. ISSN 1980-5357 versão on-line. Disponível em: https://www.scielo.br/scielo.php/script_sci_serial/lng_pt/pid_0101-4161/nrm_iso. Acesso em: 1 jul. 2020.
*   PEREIRA, José Matias. Manual de metodologia da pesquisa científica. 4. ed. rev. e atual. São Paulo: Atlas, 2016. *E-book*. ISBN 9788597008821.

## Descrição da Bibliografia Complementar
*   BAPTISTA, Makilim Nunes; CAMPOS, Dinael Corrêa de. Metodologias pesquisa em ciências: análises quantitativa e qualitativa. 2. ed. ampl. e atual. Rio de Janeiro: LTC - Livros Técnicos e Científicos, c2016. *E-book*. ISBN 9788521630470.
*   CARVALHO, Maria Cecília Maringoni de (org.). Construindo o saber: metodologia científica, fundamentos e técnicas. Campinas, SP: Papirus, 2021. *E-book*. ISBN 9786556500928.
*   DEMO, Pedro. Praticar ciência: metodologias do conhecimento científico. São Paulo: Saraiva, c2012. *E-book*. ISBN 9788502148079.
*   GIL, Antônio Carlos. Como elaborar projetos de pesquisa. 7. ed. Barueri, SP: Atlas, 2022. *E-book*. ISBN 9786559771653.
*   MARCONI, Marina de Andrade; LAKATOS, Eva Maria. Fundamentos de metodologia científica: métodos científicos, técnicas de pesquisa, elaboração de referências bibliográficas. 9. ed. atual. São Paulo: Atlas, 2021. *E-book*. ISBN 9788597026580.
*   NOVA ECONOMIA. Belo Horizonte: UFMG, Departamento de Ciências Econômicas, 1990-. Semestral. ISSN 1980-5381 versão on-line. Disponível em: http://www.scielo.br/scielo.php?script=sci_serial&pid=0103-6351&lng=en&nrm=iso. Acesso em: 21 ago. 2018.
