---
title: "GESTÃO DE PROCESSOS"
subtitle: "Extracurricular | Nota: 76"
description: "Disciplina cursada na PUC Minas como parte do currículo de Administracao, sob a orientação do(a) professor(a) Maria Luiza Fatima Costa de Proenca Doyle (Doutorado)."
categories: ["PUC Minas", "Administracao", "Gestao"]
carga_horaria: 40
nota: 76
periodo: 100
toc: true
---

## Ementa
Abordagens e conceitos sobre processos; Integração de processos e o planejamento estratégico, a estrutura organizacional e outros instrumentos gerenciais; Metodologias, técnicas e ferramentas para a melhoria de processos organizacionais; Ferramentas de modelagem, análise e redesenho de processos; Planejamento para implementação e acompanhamento de processos; Indicadores de desempenho de processos.

## Objetivos
**Objetivo Geral**
Capacitar os alunos para identificar, diagnosticar, propor alternativas, implantar e acompanhar a melhoria dos processos de negócios empregando metodologias, tecnologias e softwares aplicados na modelagem e melhoria de processos visando a inovação, eficiência e a eficácia das organizações.

**Objetivos Específicos**
*   Estabelecer a diferença entre a abordagem Funcional e a Gestão de Processos de Negócio.
*   Compreender o conceito de Processos de Negócio e a aplicação da visão de Processos nas organizações.
*   Identificar, conhecer, selecionar e aplicar metodologias, tecnologias e softwares aplicados à modelagem e melhoria de processos.
*   Desenvolver projetos de Modelagem e Melhoria de processos.
*   Compreender e aplicar as metodologias de gestão de processos, nas etapas de planejamento, implantação e avaliação de resultados com a utilização dos indicadores de desempenho.

## Métodos Didáticos
*   Aulas expositivas dialogadas,
*   Estudos de caso,
*   Trabalhos práticos,
*   Execução e discussão de Pesquisas,
*   Discussão de temas emergentes,
*   Sala de aula invertida,
*   Aprendizagem experimental,
*   Seminários

## Unidades de Ensino
1.  **Introdução à gestão por processos - 10 horas**
    O que são e por que estudar processos nas organizações? A visão Funcional e dos Processos: organização Funcional versus Organização por Processos. Tipos e hierarquia de processos. Classificação dos processos de negócios nas organizações. Tipos de Processos. Processos e Cadeia de Valor. Identificação e classificação de processos A Process Classification Framework - PCF. Apresentação da atividade prática com a PCF.
2.  **Metodologias de Análise e Modelagem de Processos - 04 horas**
    Apresentação da metodologia de análise e modelagem de processos BPM, O Ciclo BPM. Mapeamento e modelagem de processos. Modelagem As Is, Análise do As Is e proposições de melhoria para o processo futuro. Modelagem To Be.
3.  **Ferramentas de Modelagem de Processos - 06 horas**
    Técnicas de modelagem de processos. A notação BPMN (Business Process Model and Notation). Apresentação da modelagem BPMN com o Bizagi. Aplicação prática do BPMN com o Bizagi
4.  **Indicadores de desempenho de processos - 04 horas**
    Indicadores de desempenho e BSC. Apresentação da atividade prática sobre indicadores de desempenho ID.
5.  **Aplicação prática do BPM - 10 horas**
    Orientação dos grupos e apresentação do roteiro para o Projeto BPM. Orientação e acompanhamento dos grupos. Apresentação dos grupos do Projeto BPM
6.  **Prova Intermediaria, Avaliação Global e Prova de Reavaliação - 6 horas**

## Processo de Avaliação
*   Atividades individuais e em grupo - 10 pontos
*   2 avaliações intermediárias - 15 pontos/cada - 30 pontos
*   Projeto BPM - 30 pontos
*   Avaliação global - 30 pontos
*   Reavaliação - 30 pontos

## Observações
Revistas eletrônicas incluídas na bibliografia básica e complementar.

## Descrição da Bibliografia Básica
*   BPM CBOK : guia para gerenciamento de processos de negócio :corpo comum de conhecimento : v 3.0. Brasil: ABPMP, c2013. E-book
*   OLIVEIRA, Djalma de Pinho Rebouças de. Administração de processos: conceitos, metodologia e práticas. 6. ed. São Paulo: Atlas, 2019. *E-book*. ISBN 9788597021301.
*   RAI : REVISTA DE ADMINISTRAÇÃO E INOVAÇÃO = INMR - INNOVATION & MANAGEMENT REVIEW. Quadrimestral (4 em 4 meses). ISSN 2515-8961 versão on-line. Disponível em: http://www.revistas.usp.br/rai/index. Acesso em: 16 ago. 2018.
*   VALLE, Rogério; OLIVEIRA, Saulo Barbará de (org.). Análise e modelagem de processos de negócio: foco na notação bpmn (business process modeling notation). São Paulo: Atlas, 2009. *E-book*. ISBN 9788522479917.

## Descrição da Bibliografia Complementar
*   CRUZ, Tadeu. Sistemas, organização & métodos: estudo integrado das novas tecnologias de informação e introdução à gerência do conteúdo e do conhecimento. 3. ed. rev., atual. e ampl. São Paulo: Atlas, 2002. 276 p. ISBN 8522431574., Nº de Exemplares: 5.
*   CURY, Antônio. Organização e métodos: uma visão holística. 9. ed. São Paulo: Atlas, 2017. *E-book*. ISBN 9788597010039.
*   HALL, Richard H. Organizações: estruturas, processos e resultados - 8ª edição. Editora Pearson 336 ISBN 9788587918765.
*   REVISTA PRODUÇÃO ONLINE. Piracicaba, SP: Universidade Metodista de Piracicaba, 2001-. Trimestral (de 3 em 3 meses). ISSN 1676-1901 versão on-line. Disponível em: https://producaoonline.org.br/rpo/index. Acesso em: 18 ago. 2021.
*   RODRIGUES, Marcus Vinícius Carvalho. Ações para a qualidade: gestão estratégica e integrada para a melhoria dos processos na busca da qualidade e produtividade (GEIQ). 6. ed. rev. e ampl. São Paulo: Atlas, 2020. *E-book*. ISBN 9788595157156.
*   TACHIZAWA, Takeshy; SCAICO, Oswaldo. Organização flexível: qualidade na gestão por processos. São Paulo: Atlas, 1997. 335 p. ISBN 8522416044, Nº de Exemplares: 4.
